### ISSUE TITLE
Add support for datetime objects

### ISSUE THREAD

**Issue by jcrist** [jcrist/msgspec#1]
It'd be useful to add support for `datetime` objects. I'm not sure how we'd want to go about serializing these, there's a few different options:

- `datetime.datetime`: Could use the [Timestamp extension](https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type), or as a string according to e.g. ISO 8601.
- `datetime.timedelta`/`datetime.time`/`datetime.date`: Custom extension format? Or as a string per ISO 8601?

We likely need to support the extension type for timestamps, the string format may(?) be useful as well, and may provide nicer parity with other types if we decide to implement those as string formats.

**Comment by dhagrow** [comment]
Hi, just came across this library and I plan on giving it a try. You might consider [temporenc](https://github.com/temporenc/temporenc-python) for datetime objects.
