### ISSUE TITLE
Build wheels for Linux/Mac ARM

### ISSUE THREAD

**Issue by cjermain** [jcrist/msgspec#103]
With the Apple M1 using ARM, it would be valuable to support Linux and Mac ARM builds in the CI. I can take a look at this when I get a chance. I suspect is should be a small change to add the builds in the GitHub actions.

**Comment by jcrist** [comment]
Sure, I'd happily accept a PR adding this support. A quick search turned up https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon. I *think* we'd want to set:

```
CIBW_ARCHS_MACOS: x86_64 arm64
CIBW_TEST_SKIP: *_arm64
```

**Comment by newbery** [comment]
Cool. Are we close to getting this yet?
