### ISSUE TITLE
Testing 3.11

### ISSUE THREAD

**Issue by CamDavidsonPilon** [jcrist/msgspec#143]
👋 I've been testing 3.11b4 on an RPi. I'm not sure, but msgspec may need some changes? I'm not experienced enough here to know if it's an error in my installation / with RPi, or an issue with msgspec.

```
$ python3
Python 3.11.0b4 (main, Jul 12 2022, 12:12:30) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from msgspec.json import encode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/msgspec/__init__.py", line 1, in <module>
    from ._core import (
ImportError: /usr/local/lib/python3.11/site-packages/msgspec/_core.cpython-311-arm-linux-gnueabihf.so: undefined symbol: _PyObject_GC_Malloc
>>>

**Comment by jcrist** [comment]
Yeah, that looks like a 3.11 incompatibility on our end (we use some internal apis for perf reasons). Thanks for the reminder to setup testing while 3.11 is still in beta!

**Comment by jcrist** [comment]
Ok, I poked at this a bit tonight. Notes for myself for later:

- `PyHeapType_GET_MEMBERS` is now a private macro, but no change in implementation. We should just copy the macro out.
- There have been major changes to the GC api (perhaps unintentional):
  - `_PyObject_GC_Malloc` no longer is exposed. This is fine, it was never technically a public api.
  - `PyObject_GC_Del` now requires `obj` to have a valid type, previously this was only a thin layer around `PyObject_Free`. This breaks our freelist linked-list, which overloads the `ob_type` field to point to the next element in the freelist. Instead, we should use the first slot index, and never cache 0-length structs.
- There is now no public way to touch the GC allocator without providing all allocation size info through the type object itself. This means the allocation code for `IntLookup` objects will need to change (possibly just define `tp_itemsize` as `1` and hack around the api change)?
