### ISSUE TITLE
Can't use enc_hook to fix naive datetimes

### ISSUE THREAD

**Issue by tuffnatty** [jcrist/msgspec#152]
The code raises an exception when it encounters a `datetime` without `tzinfo`. It would be much better if I could fix it in `enc_hook`, but, alas, `datetime` seems to be a "supported" type, therefore `enc_hook` never gets called on it.

**Comment by jcrist** [comment]
Hmmm, that's certainly possible to do.

A few questions:

- Do your messages contain a mix of naive and aware datetimes? Or are you only using naive datetimes?
- How do you plan on treating naive datetimes? UTC? Local timezone? Something else?
- Do you plan on serializing datetimes in a different format than RFC3339 (what msgspec currently uses)?

**Comment by tuffnatty** [comment]
> * Do your messages contain a mix of naive and aware datetimes? Or are you only using naive datetimes?

I am dealing with poorly structured data from MongoDB, so I am never sure what kind of datetime I will encounter.

> * How do you plan on treating naive datetimes? UTC? Local timezone? Something else?

I attempted to convert them to UTC in enc_hook.

> * Do you plan on serializing datetimes in a different format than RFC3339 (what msgspec currently uses)?

I did not have any such plan. RFC3339 is space efficient enough for me, but if I had such a problem, I'd look at [Temporenc](https://temporenc.org), although their reference implementation in pure Python may be too slow.

I have already solved my immediate problem by fixing the data before feeding to msgspec, but I still think a hook could be useful here.

**Comment by jcrist** [comment]
Makes sense, we can definitely add this feature. I'll try to get it in before the next release.

>  (P.S.: I am using msgpack encoding. Does it also serialize to RFC3339?)

Ah, my mistake, I assumed you were using JSON. Msgpack has a [timestamp extension type](https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type) that provides a builtin efficient representation.
