### ISSUE TITLE
support arbitrary-sized integers

### ISSUE THREAD

**Issue by banteg** [jcrist/msgspec#153]
i often deal with 256-bit integers, but msgspec only appears to support up to 64-bit integers.

it would be great to still be able to encode larger integers even if it's slower.

```python
>>> json.dumps({'big': 2**256-1})
'{"big": 115792089237316195423570985008687907853269984665640564039457584007913129639935}'

>>> msgspec.json.encode({'big': 2**256-1})
OverflowError: int too big to convert
```

**Comment by jcrist** [comment]
That's possible, but most JSON implementations wouldn't be able to read those messages.

Javascript doesn't support roundtripping anything larger than a 53 bit integer, and many implementations don't support larger than an int64 (`msgspec` currently supports up to a `uint64`). Some implementations encode big (for some definition of big) integers as strings to ensure they can be read properly by all backends - something like:

```python
>>> some_json_lib.dumps({'big': 2**256-1})
'{"big": "115792089237316195423570985008687907853269984665640564039457584007913129639935"}'
```

What kind of interop do you need here? Are other systems likely to be reading these messages, or do you only need to be able to roundtrip this data using the same JSON library?

**Comment by banteg** [comment]
fair suggestion, i think i've seen them encoded as both str and hexstr representations, and your answer makes me understand why that was the case. i knew about the js limitation, people usually use different BigNumber libraries to handle large integers there, but json deserialization never crossed my mind as an obstacle.

for my case i only need interop within python, i'm evaluating using this library as a replacement for pydantic. ngl the 10x speedup sounds alluring. amazing work on performance.

**Comment by banteg** [comment]
tried handling my case using hooks, it has worked perfectly, great extensibility. you can close this issue if you want.
https://gist.github.com/banteg/5826ae7bc1ce42748e48db29f815d38b

**Comment by jcrist** [comment]
Oh nice, that was going to be my next suggestion. Glad you figured it out on your own, happy to know that the documentation was sufficient here.

I _might_ add support for encoding/decoding large integers natively in the future, but I'll close this for now.
