### ISSUE TITLE
optional doesn't work with a custom class

### ISSUE THREAD

**Issue by banteg** [jcrist/msgspec#159]
i'm trying to decode a jsonrpc response which has an optional value which i need to process in `dec_hook`.

to do this i subclass `address` class from `str`, but get a decoding error when the value is `null`. i tried both `Optional[address]` and `address | None`. it works if i change to `Optional[str]`, but i can't do the processing.

the doc says "Unions with custom types are unsupported beyond optionality (i.e. Optional[CustomType])", which implies this should be possible.

i extracted a small [sample here](https://gist.github.com/banteg/49b45f574e850f13b46e609cba143806) which includes one working and one failing case. for the failing case i get:
```python
msgspec.DecodeError: Expected `address`, got `NoneType` - at `$.to`
```

a more complete spec of what im building [is here](https://gist.github.com/banteg/cee923b6616a8f70db1e18a61b91e39c) if it's useful.

**Comment by jcrist** [comment]
Thanks for the excellent reproducible bug report - this should be fixed in #162.
