### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by AsafMahlev** [jcrist/msgspec#167]
Hey, is it planned/in the scope of the project to add support for async buffers/streams for decoding?

**Comment by jcrist** [comment]
I'm not sure what you mean by that? Can you say more about what API is missing?

**Comment by AsafMah** [comment]
Basically types like `asyncio.StreamReader` - https://docs.python.org/3/library/asyncio-stream.html#streamreader

That you need to call `await f.read()` on instead of `f.read()`.

ijson, for example, supports it - https://pypi.org/project/ijson/#asyncio-support

**Comment by AsafMah** [comment]
I guess now it doesn't accept buffers at all

**Comment by jcrist** [comment]
Yeah, msgspec will not support a case where the full message buffer isn't already available in memory. It's the user's responsibility to handle any IO to get the buffer in memory before passing it to msgspec. Closing.
