### ISSUE TITLE
mypy error with Tagged Unions

### ISSUE THREAD

**Issue by CamDavidsonPilon** [jcrist/msgspec#173]
👋 I'm hitting a mypy error: Here's my simple test:

```python
# msgspec_test.py
from msgspec import Struct
from msgspec.json import encode, decode
from typing import Union

class Automation(Struct):
    name: str
    args: dict = {}

class TemperatureAutomation(Automation, tag="temperature"):
    ...

class DosingAutomation(Automation, tag="dosing"):
    ...

class LEDAutomation(Automation, tag="led"):
    ...


value = encode(LEDAutomation(name="thing", args={}))
decode(value, type=Union[TemperatureAutomation, DosingAutomation, LEDAutomation])
```

Running `mypy msgspect_test.py` gives:

```
msgspec_test.py:20: error: No overload variant of "decode" matches argument types "bytes", "object"
msgspec_test.py:20: note: Possible overload variants:
msgspec_test.py:20: note:     def decode(buf: bytes, *, dec_hook: Optional[Callable[[Type[Any], Any], Any]] = ...) -> Any
msgspec_test.py:20: note:     def [T] decode(buf: bytes, *, type: Type[T] = ..., dec_hook: Optional[Callable[[Type[Any], Any], Any]] = ...) -> T
Found 1 error in 1 file (checked 1 source file)
```

It works fine with pyright though.

### Versions

mypy==0.971
msgspec==0.8.0
pyright==1.1.268

**Comment by jcrist** [comment]
Thanks for the excellent reproducible issue, this appears to be an upstream bug in mypy. I've filed an issue here: https://github.com/python/mypy/issues/13498.

I don't think there's much we can do about this locally - the type signatures provided should be correct as far as I can tell, and pyright does the right thing. Closing, as this requires an upstream fix.

**Comment by CamDavidsonPilon** [comment]
👍 thanks for confirming

**Comment by jcrist** [comment]
I just pushed up some type annotation changes to make mypy work better here. It still won't be able to infer the output type of `decode` *when the type-level type is a `Union`*, but at least it won't error (it infers it as `Any`).

Explicitly annotating the return type also works.

```python
# If you don't explicitly annotate `out,` mypy will infer it as `Any`
out: int | str = msgspec.json.decode(some_msg, type=int | str)
```

I still recommend using `pyright` when possible as it doesn't need these workarounds and also supports typing `Struct` constructors, but both should work now.

**Comment by CamDavidsonPilon** [comment]
Thanks for the follow up. I've been slowly moving over to pyright, too.
