### ISSUE TITLE
Interop with msgpackr record structures

### ISSUE THREAD

**Issue by e271828-** [jcrist/msgspec#179]
When optimizing, most people eventually end up with binary serialization and either combine it with a separate dictionary or build that into the serialization step.

For example, `{"long_key_name": "value"}` -> `{0: "value"}` -> `{0: 1}`

Preloading offline-computed dictionaries of common keys and values is a fairly elegant way to solve this.

Would you consider supporting [msgpackr's](https://www.npmjs.com/package/msgpackr) approach to shared record structures? I think it is probably the most popular version of this at the moment.

**Comment by jcrist** [comment]
Sorry, this is out of scope for msgspec. For handling *structured* messages in a more efficient way, we support encoding/decoding structs as arrays of their values, dropping the field names from the message entirely (see https://jcristharif.com/msgspec/structs.html#encoding-decoding-as-arrays). In practice this works very well, and results in a similar payload size reduction and improved efficiency. One benefit of this is that it works natively with other msgpack implementations, without requiring they support a custom non-standard extension.
