### ISSUE TITLE
Define schema's attribute with Python's keyword

### ISSUE THREAD

**Issue by rezayoga** [jcrist/msgspec#182]
I used msgspec to create schemas using standard Python-type annotations. How can I map the attribute that used the attribute's name as the same as one of the Python keywords because my JSON schema is using this name (-from- keyword, and without changing the name of -from- attribute)?

```
class Text(msgspec.Struct):
    body: Optional[str]

class Messages(msgspec.Struct):
    from: Optional[str]
    id: Optional[str]
    timestamp: Optional[str]
```

Thanks

**Comment by jcrist** [comment]
Thanks for opening this issue. The docs section you're looking for is https://jcristharif.com/msgspec/structs.html#renaming-field-names. You'd handle this by passing in a function to `rename` for mapping your python field names (`from_`, for example) to the
corresponding field names to use in the JSON message (`from`, for example). In this case we can do this by stripping off any trailing `_` characters:

```python
In [1]: import msgspec

In [2]: from typing import Optional

In [3]: class Messages(msgspec.Struct, rename=lambda n: n.rstrip("_")):
   ...:     from_: Optional[str]  # The python field is named `from_`
   ...:     id: Optional[str]
   ...:     timestamp: Optional[str]
   ...: 

In [4]: m = Messages("alice", "12345", "2022-09-12T12:34:56")

In [5]: msgspec.json.encode(m)
Out[5]: b'{"from":"alice","id":"12345","timestamp":"2022-09-12T12:34:56"}'
```

Does that answer your question?

In the future we might update our interface to also accept a dict of only keys to be renamed. This may be easier to use for your use case of only renaming a few fields:

```python
class Messages(msgspec.Struct, rename={"from_": "from"}):
    from_: Optional[str]
    id: Optional[str]
    timestamp: Optional[str]
```

**Comment by rezayoga** [comment]
Thanks @jcrist; sure, this solves my problem in naming.

Maybe it will be easier if the definition is like your suggestion in the future feature, only keys to be renamed.

```
class Messages(msgspec.Struct, rename={"from_": "from"}):
    from_: Optional[str]
    id: Optional[str]
    timestamp: Optional[str]
```

**Comment by jcrist** [comment]
Excellent, glad to hear it. I've added support for passing in a mapping for `rename` as described  above in #185. I'm hoping to release later this week, so that feature should be out soon. Closing!
