### ISSUE TITLE
Add HPy compatibility

### ISSUE THREAD

**Issue by pauloxnet** [jcrist/msgspec#188]
It can be interesting to add compatibility of this project with [HPy](https://github.com/hpyproject/hpy)

Maybe some HPy maintainer (es: @antocuni ) can suggest how to proceed.

**Comment by jcrist** [comment]
What benefits are you hoping to achieve with added HPy support?

**Comment by jcrist** [comment]
Closing as stale, feel free to reopen if there's more to discuss.
