### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by KhDenys** [jcrist/msgspec#207]
Hi, I’m excited to use msgspec, its performance very impressed. 

Pydantic has [released ](https://twitter.com/samuel_colvin/status/1587777932373655554)  a new rust backend with huge performance gains. Would be great to see updated benchmarks page in the docs.

**Comment by jcrist** [comment]
Pydantic V2 hasn't been released yet, they just merged a major refactor PR. I'll update the benchmarks whenever Pydantic V2 is released and up on PyPI, but not before then.

If you want to see benchmarks against their dev branch now:

- You can install the dev branch of pydantic (as well as our other benchmarking dependencies) and run the [benchmark scripts](https://github.com/jcrist/msgspec/tree/main/benchmarks) yourself. As far as I know, pydantic's public facing API hasn't changed, they should just run.
- A few months ago Samuel Colvin asked me for a comparison benchmark against pydantic V2, which I wrote up [here](https://gist.github.com/jcrist/d62f450594164d284fbea957fd48b743?permalink_comment_id=4256424#gistcomment-4256424). This is using `pydantic-core` directly, I'd expect going through `pydantic` itself to add a mild amount of overhead. In my measurements at the time, pydantic v2 looks to be anywhere between 5-20x slower than msgspec, schema dependent.

**Comment by astrojuanlu** [comment]
Time to update the bar chart? https://gist.github.com/jcrist/d62f450594164d284fbea957fd48b743?permalink_comment_id=4619455#gistcomment-4619455
