### ISSUE TITLE
Access fields data

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#227]
Hi again,

So I encountered an issue when trying to integrate msgspec into the internal of our libraries, namely - there is no way for me to easily access the field information on a struct.

The `__struct_fields__` attribute only offers a tuple of field names. If I want to access the metadata regarding each field I have to result to some rather inefficent methods such as inspecting the attributes, which is very slow.

I would like to regard a simple and fast way to get the following information about a field: its typing, any default value defined for it, and other meta data available.

**Comment by jcrist** [comment]
Can you comment more on your use case? What are you trying to do with this information?

**Comment by Goldziher** [comment]
We do all sorts of stuff with it - we construct api documentation, we generate factories for testing, and we pre-calculate when parameters are required for what routes using it.

**Comment by Goldziher** [comment]
see here: https://github.com/starlite-api/starlite/blob/main/starlite/signature.py

**Comment by jcrist** [comment]
> I would like to regard a simple and fast way to get the following information about a field: its typing, any default value defined for it, and other meta data available.

What do you mean by "other meta data"? `msgspec.Struct` types have lots of configuration options, all of which are introspectable on the type itself. Knowing more about what you want to do with things and what information you're missing would be helpful.

For a simple start of things, you might find the following utility useful:

```python
import msgspec
from typing import Union, Any, Type, get_type_hints


NO_DEFAULT = object()


class Field(msgspec.Struct, frozen=True):
    name: str
    encode_name: str
    default: Any
    type: Type


class StructInfo(msgspec.Struct, frozen=True):
    fields: tuple[Field, ...]
    tag_field: Union[str, None]
    tag: Union[str, None]
    array_like: bool


def struct_info(cls: Type[msgspec.Struct]) -> StructInfo:
    hints = get_type_hints(cls)

    n_fields = len(cls.__struct_fields__)
    n_defaults = len(cls.__struct_defaults__)
    n_required = n_fields - n_defaults

    fields = tuple(
        Field(name, encode_name, default, hints.get(name, Any))
        for name, encode_name, default in zip(
            cls.__struct_fields__,
            cls.__struct_encode_fields__,
            (NO_DEFAULT,) * n_required + cls.__struct_defaults__,
        )
    )

    return StructInfo(
        fields=fields,
        tag_field=cls.__struct_tag_field__,
        tag=cls.__struct_tag__,
        array_like=cls.array_like
    )
```

This gets you:

- All fields available on a struct, including
  - The field name
  - The encoded field name (in case that differs from the python name, e.g. `field_one` in python & `fieldOne` in JSON)
  - The field type
  - The field default value, or `NO_DEFAULT` if the field has no default
- The `tag_field` and `tag` if the Struct is "tagged" (see https://jcristharif.com/msgspec/structs.html#tagged-unions)
- Whether the struct is `array_like` (see https://jcristharif.com/msgspec/structs.html#encoding-decoding-as-arrays)

> we construct api documentation

You might be interested in our existing [JSON schema generation functions](https://jcristharif.com/msgspec/jsonschema.html). These generate JSON schema from any types that `msgspec` supports, including proper translation of [constraint annotations](https://jcristharif.com/msgspec/constraints.html). If these functions don't work for your use case, please let me know if there are ways we could change them to make them more useful.

**Comment by Goldziher** [comment]
The above is preceisely what I was asking not to do 😉 . I know how to access type hinting, or how to inspect data on a class. This though is highly inefficent, and I was asking for an easy way to get the data that is already there. In pydantic I can simply access the `__fields__` attributes, which stores a mapping of `FieldInfo` instances and includes all the information about the parsed typing data etc. Also note whats called `sub_fields` in pydantic, which basically makes fields into a sort of syntax tree for typing information. 

As for schema generation, I already have facilities to generate schema as required at present. What I need is a simple way to get the individual type values and any constraints defined for a field so I can generate OpenAPI specs for a particular handler.

On the point of JSON schema generation - does this library support custom types and custom JSON schema generation for these? This is one feature of pydantic that could be very useful to have here.

**Comment by jcrist** [comment]
> I know how to access typing information, but this is not very efficient.

Are you accessing this information in a hot-loop? Does this part of your code need to be performant? What are the performance requirements?

Even with `from __future__ import annotations` I'm still seeing a pure-python implementation of type info processing running at ~200 microseconds for a large-ish struct. Do you need it to be faster than that?

The internal type representation of msgspec isn't exposed at the python layer, and couldn't be without having to translate between it and accessible python objects (so there will always be 1-2 new allocations per field on access). *If* I wrote up some code to translate the internal representation into python objects on access, the main thing avoided would be a single `get_type_hints` call per struct, which might shave off ~150us per struct *if `__future__.annotations` is used* (the change would be negligible if not). However, the internal type representation doesn't store JSON-schema specific metadata like `title`/`description`/..., and changing that would be tricky (very tricky).

I *could* write up a pure python implementation of something like:

```python
def type_info(cls: Type) -> TypeInfo:
    """Get the type info tree for a specific type, as msgspec will see it"""
    ...

class TypeInfo:
    type: Type
    default: Any
    sub_types: tuple[TypeInfo]
    ...
```

this would still have the overhead of `get_type_hints`, but we could `lru_cache` that or something if that mattered. Knowing how frequently you access this information, whether it's in a hot path (hopefully not), and what the performance requirements are would be helpful.

**Comment by jcrist** [comment]
> As for schema generation, I already have facilities to generate schema as required at present

Since the generated schemas will have to match how the validation is implemented (which is msgspec specific), is there a reason not to use msgspec's builtin facilities for generating schemas? If you're duplicating this code in starlite, you'll naturally have to interpret the constraints and types the same way we do here.

> On the point of JSON schema generation - does this library support custom types and custom JSON schema generation for these?

Yes, we do support custom types, although not as flexibly as pydantic (in my experience though the support is enough). See https://jcristharif.com/msgspec/extending.html#mapping-to-from-native-types.

**Comment by Goldziher** [comment]
> > I know how to access typing information, but this is not very efficient.
> 
> Are you accessing this information in a hot-loop? Does this part of your code need to be performant? What are the performance requirements?
> 
> Even with `from __future__ import annotations` I'm still seeing a pure-python implementation of type info processing running at ~200 microseconds for a large-ish struct. Do you need it to be faster than that?
> 
> The internal type representation of msgspec isn't exposed at the python layer, and couldn't be without having to translate between it and accessible python objects (so there will always be 1-2 new allocations per field on access). *If* I wrote up some code to translate the internal representation into python objects on access, the main thing avoided would be a single `get_type_hints` call per struct, which might shave off ~150us per struct *if `__future__.annotations` is used* (the change would be negligible if not). However, the internal type representation doesn't store JSON-schema specific metadata like `title`/`description`/..., and changing that would be tricky (very tricky).
> 
> If sufficient, I'd rather write up a pure python implementation, which would be easier to include all the information available. Something like:
> 
> ```python
> def type_info(cls: Type) -> TypeInfo:
>     """Get the type info tree for a specific type, as msgspec will see it"""
>     ...
> 
> class TypeInfo:
>     type: Type
>     default: Any
>     sub_types: tuple[TypeInfo]
>     ...
> ```
> 
> this would still have the overhead of `get_type_hints`, but we could `lru_cache` that or something if that mattered. Knowing how frequently you access this information, whether it's in a hot path (hopefully not), and what the performance requirements are would be helpful.

This solution would be great. We are doing preemptive calculation and caching on bootstrap, so performance is more or less guaranteed on our end. 

For the other library I mentioned, the testing factories one, we are generating data on the fly, but this is not meant to be production code.

**Comment by Goldziher** [comment]
> > As for schema generation, I already have facilities to generate schema as required at present
> 
> Since the generated schemas will have to match how the validation is implemented (which is msgspec specific), is there a reason not to use msgspec's builtin facilities for generating schemas? If you're duplicating this code in starlite, you'll naturally have to interpret the constraints and types the same way we do here.
> 
> > On the point of JSON schema generation - does this library support custom types and custom JSON schema generation for these?
> 
> Yes, we do support custom types, although not as flexibly as pydantic (in my experience though the support is enough). See https://jcristharif.com/msgspec/extending.html#mapping-to-from-native-types.

We generate openapi documentation using this library, which we also maintain: https://github.com/starlite-api/pydantic-openapi-schema

We might migrate this in the future, but it's not slated for migration at present.

**Comment by Goldziher** [comment]
BTW, this is not actionable at present since this is untyped and undocumented:

<img width="584" alt="Screenshot 2022-12-09 at 21 18 31" src="https://user-images.githubusercontent.com/30733348/206789312-cc4fc2b0-3071-47b9-99f5-04c440fdf9ad.png">

**Comment by jcrist** [comment]
> so, any plans on adding this utility?

Yes, it just may take a bit. This is purely a hobby project done on my own time.

**Comment by Goldziher** [comment]
> > so, any plans on adding this utility?
> 
> Yes, it just may take a bit. This is purely a hobby project done on my own time.

I understand. We also develop Starlite as a "hobby" - although a very serious one. This is the main blocker for us to migrate our internal parsing mechanism to using msgspec, which we are pretty eager on. Lemme know if there is anything I can help with.
