### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by jakirkham** [jcrist/msgspec#23]
In addition to wheels, it would be good to have a conda-forge package of this as well to aid with Conda installations

**Comment by jcrist** [comment]
See https://github.com/conda-forge/staged-recipes/pull/14139

**Comment by jakirkham** [comment]
Thanks Jim! 😀

**Comment by jakirkham** [comment]
Feedstock is now live ( https://github.com/conda-forge/msgspec-feedstock ).

Packages have been built and uploaded. They are currently mirroring to CDN, but that should be done in 10-20mins
