### ISSUE TITLE
Dataclasses bug: Encoding includes unspecified instance attributes

### ISSUE THREAD

**Issue by provinzkraut** [jcrist/msgspec#233]
When encoding a dataclass, instance attributes that aren't dataclass-fields are included in the result:

```python
import dataclasses
import msgspec


@dataclasses.dataclass
class Foo:
    id: int


foo = Foo(id=1)
foo.bar = "test"


print(msgspec.json.encode(foo))
print(msgspec.json.encode(dataclasses.asdict(foo)))

assert msgspec.json.encode(foo) == msgspec.json.encode(dataclasses.asdict(foo))
```

This is problematic because it differs from `dataclasses.asdict`, and in turn makes `mgspec` incompatible with `pydantic.dataclasses`:

```python
from dataclasses import asdict

import msgspec
from pydantic.dataclasses import dataclass


@dataclass
class Foo:
    id: int


foo = Foo(id=1)


print(msgspec.json.encode(foo))
print(msgspec.json.encode(asdict(foo)))
```

**Comment by jcrist** [comment]
I'd argue you shouldn't be setting attributes on a dataclass that aren't part of its definition. Doing so is violating the type annotations.

FWIW, we match the behavior of `orjson` here, which is what was asked in #57.

```python
In [1]: import dataclasses

In [2]: @dataclasses.dataclass
   ...: class Point:
   ...:     x: int
   ...:     y: int
   ...: 

In [3]: p = Point(1, 2)

In [4]: import msgspec, orjson

In [5]: msgspec.json.encode(p)
Out[5]: b'{"x":1,"y":2}'

In [6]: orjson.dumps(p)
Out[6]: b'{"x":1,"y":2}'

In [7]: p.z = 3

In [8]: msgspec.json.encode(p)
Out[8]: b'{"x":1,"y":2,"z":3}'

In [9]: orjson.dumps(p)
Out[9]: b'{"x":1,"y":2,"z":3}'
```

**Comment by jcrist** [comment]
> This is problematic because it differs from dataclasses.asdict, and in turn makes mgspec incompatible with pydantic.dataclasses

Ope, sorry, I missed this part. You're using pydantic's `dataclass` decorator - that doesn't actually create a dataclass, that creates a pydantic thing that is dataclass-like. That's annoying :/.

One thing we could do to avoid this is skip encoding attributes that have leading underscores (or maybe only double-leading underscores?). `orjson` does this, which is why you don't see that behavior there. There's no performant way to access the defined list of fields for a dataclass, so I'd prefer something that we can filter attributes on that doesn't require touching `__dataclass_fields__`. Thoughts?

**Comment by provinzkraut** [comment]
> FWIW, we match the behavior of orjson here, which is what was asked in https://github.com/jcrist/msgspec/issues/57.

Not quite. Pydantic dataclasses work with orjson:

```python
from dataclasses import asdict

import msgspec
from pydantic.dataclasses import dataclass
import orjson


@dataclass
class Foo:
    id: int


foo = Foo(id=1)


assert orjson.dumps(foo) == orjson.dumps(asdict(foo))
assert msgspec.json.encode(foo) == msgspec.json.encode(asdict(foo))
```

It seems like `orjson` is special casing instance attributes with a leading underscore:

```python
from dataclasses import asdict, dataclass

import orjson


@dataclass
class Foo:
    id: int


foo = Foo(id=1)
foo._bar = True
foo.__bar = True


assert orjson.dumps(foo) == orjson.dumps(asdict(foo))
```

**Comment by provinzkraut** [comment]
Only saw your comment after I replied:

> You're using pydantic's dataclass decorator - that doesn't actually create a dataclass, that creates a pydantic thing that is dataclass-like

It actually creates a proper dataclass, it just adds some extra functionality. But that's not relevant for this is think.

> One thing we could do to avoid this is skip encoding attributes that have leading underscores (or maybe only double-leading underscores?). orjson

Yes, I think that's a reasonable approach.

**Comment by provinzkraut** [comment]
> Mmk. Should be a quick fix; expect a patch release in the next day or two.

Perfect, thanks a lot!

 > If you have time, could you check if there are any other incompatibilities so we can batch them all in one release?

I just ran our test suites against the latest release and this was the only thing that popped up. Nothing else comes to mind at the moment, but should I come across anything else I'll let you know!

**Comment by jcrist** [comment]
Should be fixed by #234.

**Comment by provinzkraut** [comment]
Can confirm, everything works fine with that branch!

**Comment by jcrist** [comment]
Release bots have been kicked off, should be up on PyPI soon: https://github.com/jcrist/msgspec/actions/runs/3650859373.

Thanks for all the excellent issue reports lately, it's been very helpful for improving this library.

**Comment by provinzkraut** [comment]
Nice! That means we can ship Starlite with `msgspec` as soon as the release is out!

> Thanks for all the excellent issue reports lately, it's been very helpful for improving this library.

Well thanks for this awesome library and your continued effort to improve it! (=
