### ISSUE TITLE
Support serializable key in dict (not only str)

### ISSUE THREAD

**Issue by metanqy** [jcrist/msgspec#241]
val = (record_id, msgspec.json.encode(results))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dict keys must be strings
<img width="556" alt="image" src="https://user-images.githubusercontent.com/1705152/208073556-bf06d0da-649d-4ad4-8c07-4894d06219cd.png">

Doesn't support int key in dict.

**Comment by jcrist** [comment]
Can you clarify what you're asking for here? What output do you expect for

```python
>>> msgspec.json.encode({1: "foo"})
```

**Comment by provinzkraut** [comment]
@metanqy this is a question of strictness. Some json libraries are lenient here and encodes it as ```{"1":"foo"}```.

- stdlib: lenient
- orjson: strict
- ujson: lenient

I think being strict is a feature and like the fact that msgspec is strict in this case.

**Comment by jcrist** [comment]
After a bit of review of prior art, I think supporting integer keys (serialized too/from strings) for JSON makes sense. This is commonly supported by other JSON libraries across several different languages. Further, the standard `citm_catalog.json` benchmark file has a schema that makes use of integer-keys in the schema.

I've added support for this in #243.
