### ISSUE TITLE
Adding aliases for fields

### ISSUE THREAD

**Issue by ZeN220** [jcrist/msgspec#246]
For example, i have json by like:
```
{
    "$field": "value",
    "from": "another_value"
}
```
I cannot be create a structs with this fields, because this names of fields do not fit the requirements of python. In this case, aliases can be help:
```python
class A(msgspec.Struct):
    field: str = msgspec.Field(alias="$field")
    from_: str = msgspec.Field(alias="from")
```
I can't be sure, that this functionality doesn't exist. But if it exists, please tell me about it.

**Comment by jcrist** [comment]
This is supported through the `rename` keyword passed as part of the Struct definition. Does this docs section help? https://jcristharif.com/msgspec/structs.html#renaming-field-names

In your case you'd do:

```python
In [1]: import msgspec

In [2]: class A(msgspec.Struct, rename={"field": "$field", "from_": "from"}):
   ...:     field: str
   ...:     from_: str
   ...: 

In [3]: msgspec.json.encode(A(field="foo", from_="bar"))
Out[3]: b'{"$field":"foo","from":"bar"}'
```
