### ISSUE TITLE
Future Support for Custom Binary Protocols

### ISSUE THREAD

**Issue by AndrewSpittlemeister** [jcrist/msgspec#263]
Hey, I really like this library and have started using it for a few projects of my own. In my opinion, it has integrated well into the ecosystem in a very pythonic manner.

I'm wondering if it is in the cards to include support for custom binary protocols (kind of like Python's `struct` module). I authored a similar project called [bytechomp](https://github.com/AndrewSpittlemeister/bytechomp) that is built on top of the `struct` module built-in. It works well and is fast enough for my needs, but many of those who use the `struct` module are working on embedded/constrained hardware. My project is pure python and I'm sure could be sped up if some things were lowered down into C or Rust but I don't currently have a lot of bandwidth to do so.

So this post is mainly to gauge the interest of this feature from the authors and users. I'd also be happy to discuss possible paths forward if there is interest.

**Comment by jcrist** [comment]
Hi @AndrewSpittlemeister! `bytechomp` looks really interesting! I'm curious - what use cases do you have for writing custom protocols? Are there reasons not to build off existing standards like `msgpack`/`json`/`protobuf`?

My gut reaction is I don't think something like `bytechomp` belongs in `msgspec` itself, but I'd like to hear more about what you're thinking here. If there's metadata or utilities we can expose to make it easy to extend msgspec outside of the library itself that might also be a good path forward.

**Comment by jcrist** [comment]
@AndrewSpittlemeister any reply to the above?

**Comment by jcrist** [comment]
Closing as stale for now, please feel free to reopen if you want to continue the conversation.
