### ISSUE TITLE
Force struct validation / parse nested structures

### ISSUE THREAD

**Issue by aedify-swi** [jcrist/msgspec#265]
Hello!

Another issue that appeared last week: I am parsing nested json structures from external APIs where I am only interested in a subset of the data or my items are nested below some other key. Is there a way to use msgspec for this? 

```json
{
  "data": 
    [{
      "somekey": [...],
      "mykey": {
        "fieldA": null,
        "fieldB": 1
      }}]
}

```
And the corresponding struct:

```python

class MyStruct(Struct):
    field_a: datetime | None
    field_b: int
```
If I didn't miss anything, I can not use msgspec decode for this (while getting the correct types/validation). Is there a way to do this today (apart from encoding parts of the dict back to str/bytes)? 

Alternatively, would you consider adding one of the following  functionalities?

A) load the json into a dict and create MyStruct from it's sub-dict – passing some flag to force validation would be great for this. 
B) a way to tell the decoder where to look for the struct of interest, e.g. `msgspec.json.decode(json, path="data.mykey")`

Thanks a lot!

**Comment by jcrist** [comment]
Hi @aedify-swi - if I understand correctly, you're trying to parse an inner JSON object that's part of some larger JSON object, ignoring some leading path.

If you want typed decoding, msgspec requires a schema from the object root up to the point you wish to decode. In practice I haven't found this to be too onerous - most JSON objects are relatively shallow, and msgspec doesn't require a full schema definition. In your case above you handle this like:

```python
import msgspec
from datetime import datetime

data = """
{
  "data":
    [{
      "somekey": [1, 2, 3],
      "mykey": {
        "fieldA": null,
        "fieldB": 1
      }}]
}
"""

class MyStruct(msgspec.Struct, rename="camel"):
    field_a: datetime | None
    field_b: int


class Inner(msgspec.Struct):
    mykey: MyStruct


class Outer(msgspec.Struct):
    data: list[Inner]


res = msgspec.json.decode(data, type=Outer)

for obj in res.data:
    print(obj.mykey)
```

Alternatively you may use [msgspec.defstruct](https://jcristharif.com/msgspec/api.html#msgspec.defstruct) to automatically define the outer structs. You might find this issue comment relevant here: https://github.com/jcrist/msgspec/issues/171#issuecomment-1222880185.

**Comment by jcrist** [comment]
Closing this as resolved. If you have further questions feel free to reopen (if relevant), or open a new issue. Thanks!
