### ISSUE TITLE
Decimal support

### ISSUE THREAD

**Issue by LukasKrocek** [jcrist/msgspec#304]
### Description

Hello, 

in project docs I found decimal among supported types:
https://jcristharif.com/msgspec/supported-types.html#decimal

when i am trying 

```import decimal
import msgspec

x = decimal.Decimal("1.2345")

msg = msgspec.json.encode(x)
```

I am getting error:  `Encoding objects of type decimal.Decimal is unsupported`. I tried in python 3.8, 3.10, 3.11

Thank you :)

**Comment by jcrist** [comment]
Sorry, yeah, this feature hasn't been released yet. I'm hoping to get a release out this week; for now you can [install from GitHub](https://jcristharif.com/msgspec/install.html#installing-from-github).
