### ISSUE TITLE
question: how to query options used to create Struct

### ISSUE THREAD

**Issue by tlambert03** [jcrist/msgspec#327]
### Description

I'm wondering if there's a way to query the configuration kwargs passed to the Struct metaclass.
For example, how might I tell if a Struct was defined with `class M(msgspec.Struct, frozen=True)` (without trying to set an attribute and catching the exception)

**Comment by jcrist** [comment]
Hi! Thanks for opening this. This information was previously available in an intentionally undocumented interface:

```python
In [1]: import msgspec

In [2]: class Point(msgspec.Struct, frozen=True):
   ...:     x: int
   ...:     y: int
   ...: 

In [3]: Point.frozen
Out[3]: True
```

This interface was inconsistent across config parameters, and was mostly exposed for testing purposes. It's been something I've been meaning to redo, and this issue provided the motivation to do so. I've pushed up a fix in #328 that adds a new public (and documented) interface for accessing config parameters on a Struct. They're now all collected as attributes accessed off `__struct_config__`, available on both the struct type and instances:

```python
In [1]: import msgspec

In [2]: class Point(msgspec.Struct, frozen=True):
   ...:     x: int
   ...:     y: int
   ...: 

In [3]: Point.__struct_config__.frozen
Out[3]: True

In [4]: x = Point(1, 2)

In [5]: x.__struct_config__.frozen
Out[5]: True
```

**Comment by jcrist** [comment]
This has now been merged. It's probably going to be ~2 weeks until the next release (I'm offline for the next week or so). Until then you can try this out by installing from GitHub: https://jcristharif.com/msgspec/install.html#installing-from-github

**Comment by tlambert03** [comment]
Awesome thanks!
