### ISSUE TITLE
Setting kw_only to True breaks omit_defaults

### ISSUE THREAD

**Issue by AsiPanda** [jcrist/msgspec#340]
### Description

When I create a struct with kw_only=True and omit_defaults=True, the default values are still rendered. 
Removing kw_only solves this issue.

**Comment by jcrist** [comment]
Thanks for opening this. I'm unable to reproduce this issue, can you provide a minimal example that demonstrates the bug?

**Comment by AsiPanda** [comment]
Thank you for your response.
I have tried to reproduce it again (with the same code), but somehow it worked this time. It must have been due to something else I have done, although I am completely unaware of any such potential conflicts.

Sorry for taking your time; I am closing this.
