### ISSUE TITLE
How to use "from_builtins" with custom types.

### ISSUE THREAD

**Issue by lorien** [jcrist/msgspec#341]
### Description

Hello,
I did not find any sort of chat/mailing list/forum. So I'll send my question here.
Is there a way to process custom types with "from_builtin".
Here is example:
```python
import msgspec

class Int64(int):
    pass

class Box(msgspec.Struct):
    number: int

data = {"number": Int64(1)}
msgspec.from_builtins(data, type=Box)
```
I got this error: "TypeError: from_builtins doesn't support objects of type 'Int64'"

This issue is raised when I try to load into struct a data received from mongodb using pymongo library. It produces objects with simple (python builtin) data types where long integers are wrapped into "bson.int64::Int64" type.

**Comment by jcrist** [comment]
Thanks for opening this. Unfortunately currently this isn't supported, but in this particularly case the fix should be fairly straightforward.

I'm not a mongodb user, so first a few (possibly naive) questions:

- When working with bson data, are most users using the `bson` library that ships with `pymongo`? There's an alternative `bson` library [here](https://github.com/py-bson/bson) that appears to be an outdated version of the one that ships with `pymongo`. In that version the `Int64` type doesn't subclass from `int`.

- From looking at pymongo's [docs](https://pymongo.readthedocs.io/en/stable/api/bson/index.html), it appears there's a few other custom types that `bson.decode` may return. Which of these do we _need_ to support to be useful for most users? `Int64` and `Binary` would be easy (provided binary always maps to bytes), the others would be harder.

Anyway, I _think_ the easiest fix here would be to support subclasses of builtin types as inputs to `from_builtins`, and support casting those to their supported builtin equivalents (so `Int64` -> `int` would work). For your use case we'd only need to support `int` subclasses (and maybe `bytes` subclasses for `Binary`), but for parity I'd probably make this include any subclass of a supported builtin type. Thoughts?

**Comment by lorien** [comment]
I can't say anything about other pymongo users' use cases. I use pymongo strictly for my needs as a storage for documents which contain simple data types: int, float, str, bool, list. I even do not use raw bytes fields.

One thing, I can say for sure about pymongo/mongodb usage it is what there is always a "_id" field in a document. It is ObjectId type: https://pymongo.readthedocs.io/en/stable/api/bson/index.html#bson.ObjectId It is just an information. Personally I do not need to process ObjectId with msgspec. I can always load document, then take its subpart (field with a data) and pass it to "msgspec.from_builtins". 

Regarding other BSON libs. Most of pymongo users do not work with BSON data. BSON is low-level serialization format. When a user receives a document from MongoDB with a pymongo library, the document is already converted to a python dict with a values of python's builtin types. So, yeah, most of pymongo users works (implicitly) with bson library shipped with pymongo.

Honestly, by reading documentation and googling, I did not get what enc_hooh and dec_hook does. My first idea was that these functions might be used to convert unknown types like "Int64" into known builtin types. But it looks, it does not work this way.

So, maybe I do not understand something, but one of the solution for "from_builtin" could be giving a user ability to define callbacks which convert unknown types into known builtin types.
