### ISSUE TITLE
Support renaming struct fields through `msgspec.field`

### ISSUE THREAD

**Issue by jcrist** [jcrist/msgspec#355]
### Description

Sometimes you want/need to have the field names on `msgspec.Struct` objects differ from the names used when encoding/decoding those structs. This may be due to styling issues (perhaps your JSON schema uses `camelCase` for names, while python recommends `snake_case`), or may be due to the field names not being valid Python identifiers (e.g. `"from"`, `"$type"`, `"field.with.dots"`, ...).

Currently `msgpsec` supports [renaming struct fields](https://jcristharif.com/msgspec/structs.html#renaming-field-names) for encoding/decoding purposes through the `rename` config option on the struct definition.

This takes one of:
- A function from the python attribute name to encode name (e.g. `rename=str.upper`).
- A mapping from python attribute name to encode name (e.g. `rename={"my_field": "myField"}`)
- One of a variety of renaming strategies for common naming patterns (`rename="camel"` for camelCase renaming)

This works, but in some cases it might be nice to write configuration specific to a field local to that field, rather than on the struct class itself. Now that we have `msgspec.field`, we could add a new `name` parameter there to support this.

```python
from msgspec import field

class Person(Struct):
    first_name: str = field(name="firstName")
    last_name: str = field(name="lastName")

# instead of

class Person(
    Struct,
    # In this particular case rename="camel" would also work
    rename={"first_name": "firstName", "last_name": "lastName"}
):
    first_name: str
    last_name: str
```

The old pattern isn't going away - I think both have their uses. But for cases where you only want to rename one or two fields, I think keeping the name closer to the field itself may be cleaner.

The issue is how these abstractions compose, especially in the face of inheritance. Currently subclassing with `rename=something` is kinda wonky.

**Current Behavior**

- If a base class configures `rename=...` and a subclass doesn't change it, the base class behavior is used.
- If a subclass configures `rename=...`, the new rename config is applied to all fields on the subclass, *including any defined on the base class*.

This behavior seemed useful originally when only strategies like `rename="camel"` were implemented. This way you could set some common config on a shared base class, then let the strategy apply everywhere. You could also subclass an existing class and override the renaming to use a new strategy for the whole class:

```python
class Person(Struct):
    first_name: str
    last_name: str

json.encode(Person("alice", "munro"))
# > b'{"first_name": "alice", "last_name": "munro"}'

class PersonCamel(Person, rename="camel"):
    # A version of `Person`, using camelCase for naming
    pass

json.encode(PersonCamel("alice", "munro"))
# > b'{"firstName": "alice", "lastName": "munro"}'
```

However, when renaming specific fields using a mapping, then subclassing to add a new field, the behavior is unexpected.

```python
class Person(Struct, rename={"first_name": "firstName"}):
    first_name: str

class Person2(Person, rename={"address": "streetAddress"}):
    address: str

# Since Person2 configured `rename`, the original renaming scheme is
# dropped. This means that `first_name` in Person2 isn't renamed
```

I don't expect most users to run into these issues, as most users won't be subclassing from existing struct definitions to add new fields. However, we do need to make sure our behavior here is intuitive, useful, and consistent.

**Proposed Behavior**

Right now I'm leaning towards:

- `rename` is _not_ inherited. It only applies to fields defined on that struct definition.
- The *effects* of `rename` on a base struct are inherited though. Any renamed fields will still have their renamed name used in the subclassed struct. This means that in the example above `Person2` would have fields `firstName` and `streetAddress`.
- If a field has a `field(name=...)` configured on it, any `rename=...` config set on the struct is ignored for that field alone. This lets users define say `rename="camel"` on the struct, and override this for one or more fields to fix things manually as needed.

```python
from msgspec import Struct, field, json

class BaseClass(Struct, rename="camel"):
    field_a: int
    field_b: int = field(name="b")

json.encode(BaseClass(1, 2))
# > b'{"fieldA": 1, "b": 2}'

class SubClass(BaseClass):
    field_c: int
    field_d: int = field(name="d")

json.encode(SubClass(1, 2, 3, 4))
# > b'{"fieldA": 1, "b": 2, "field_c": 3, "d": 4}'

class SubClass2(BaseClass, rename="upper"):
    field_e: int

json.encode(SubClass2(1, 2, 3, 4, 5))
# > b'{"fieldA": 1, "b": 2, "field_c": 3, "d": 4, "FIELD_E": 5}'
```

I think this behavior is pretty intuitive - the class-level `rename` option only affect fields defined on that struct itself. It doesn't retroactively affect any fields defined on base classes, or affect any future subclasses.

One downside of this though is you can no longer subclass a struct and rename existing field (as done in the `PersonCamel` example above). I'm not sure how important that use case is - I've personally never needed it.

Thoughts?

**Comment by jcrist** [comment]
cc @provinzkraut for thoughts, since I _think_ you may be making use of this feature?

**Comment by provinzkraut** [comment]
> cc @provinzkraut for thoughts, since I think you may be making use of this feature?

Definitely am, thanks for the consideration! This and the generic structs are what currently keep me from migrating yet another thing to msgspec, so this getting implemented is definitely something I'm looking forward to!

> as most users won't be subclassing from existing struct definitions to add new fields 

I think this is not the case at all. While I haven't seen many usages of `Struct` in the field yet, I think pydantic's `BaseModel` is comparable, and creating a common base class is incredibly common, and something I personally make extensive use of in virtually all my projects. So I think this use case is definitely worth to consider.

> rename is not inherited

A counter example for when this would be desirable:

```python
class Header(rename=lambda name: name.replace("_", "-")):
  ...  # some common logic / fields here


class CSPHeader(Header):
  connect_src: str | None
  defautl_src: str | None
  # etc.
```

if `rename` is not inherited, you'd need to explicitly re-define it, and *intuitively* I'd expect it to work, just because I'd expect everything else regarding classes to be inherited by default. 


> I think this behavior is pretty intuitive - the class-level rename option only affect fields defined on that struct itself. It doesn't retroactively affect any fields defined on base classes, or affect any future subclasses.

How about a solution where the effects of `rename` only apply downwards the MRO? This would be the most intuitive to me, since it's closest to how regular classes behave.

<hr>

No comments on the `field(name=...)` functionality from my side, that's how I would have proposed this in a feature request.

**Comment by jcrist** [comment]
> How about a solution where the effects of rename only apply downwards the MRO? This would be the most intuitive to me, since it's closest to how regular classes behave.

I like it! I think this hits all the use cases (except renaming existing fields defined in a base class, but :shrug: if that's even a real use case). It also seems intuitive to me, thanks for the suggestion!
