### ISSUE TITLE
Improve the type hints on `msgspec.structs.asdict` and `msgspec.structs.astuple`

### ISSUE THREAD

**Issue by guacs** [jcrist/msgspec#359]
### Description

Would it be possible to add better type hints on the `asdict` and `astuple` helper methods? Right now the type is `dict` which is resolved as `dict[Unknown, Unknown]` by type checkers like Pyright. This then causes an error as shown below:

```python
from msgspec import Struct
from msgspec import structs

class Point(Struct):

    x: int
    y: int

p = Point(1, 2)

# Causes pyright to complain the following:
# Type of "p_dict" is partially unknown
# Type of "p_dict" is "dict[Unknown, Unknown]"
p_dict = structs.asdict(p)
```

I was thinking a simple fix would be to mark the return type as `dict[str, Any]` and `tuple[Any, ...]` as shown below.

```python
# Current version
def asdict(struct: Struct) -> dict: ...
def astuple(struct: Struct) -> tuple: ...

# Proposed version
def asdict(struct: Struct) -> dict[str, Any]: ...
def astuple(struct: Struct) -> tuple[Any, ...]: ...
```

Is there something I'm missing in my thought process, or would this be possible?

**Comment by jcrist** [comment]
Makes sense to me! Should be fixed by #360.
