### ISSUE TITLE
Segfault when using `dict=True` on Python 3.11

### ISSUE THREAD

**Issue by AsiPanda** [jcrist/msgspec#362]
### Description

When using this library in Python 3.11(both patch .0 and .2), I get a segmentation fault when using `dict=True`.

It seems that this has something to do with garbage collection or object destruction because it is created normally and I can interact with it until it exits the `main` scope.

Example code:
```python
from msgspec import Struct


class Record(Struct, dict=True):
    name: str


def main():
    Record(name="bye python")


if __name__ == "__main__":
    main()

```

Expected behaviour:
- Program exits silently with exit code 0

Actual behaviour:
- `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

**Comment by jcrist** [comment]
Thanks for opening this issue, I can confirm that the above example reproduces it on Python 3.11. I'll try to get this fixed sometime this week and push a patch release out.
