### ISSUE TITLE
"DecodeError('Input data was truncated')"

### ISSUE THREAD

**Issue by jose-gomez-evinex** [jcrist/msgspec#371]
### Description

Hello, 

I've been struggling with this for a few days already and can't find a solution.

I've developed a small django app that reads big .json files and decodes them in order to build some objects and store them in the DB using django ORM.

In development it works like a charm. (congrats, your tool is just amazingly fast and easy to use!)

The problem appeared in production (hosted in heroku).

Right now I'm reading the file like this:

```python
        decoder = msgspec.json.Decoder(type=Catalog)
        response = requests.get(url)
        response.raise_for_status()
        data = response.content
        catalog = decoder.decode(data)  # Error: msgspec.DecodeError: Input data was truncated
```

Not sure if I begin to understand the error. Could it be something to do with memory? Is there any better way of doing this?

Thank you!

**Comment by jcrist** [comment]
I'm sorry you're having this issue. The error indicates that the input JSON was malformed in some way that means it's missing one or more trailing characters. This is _likely_ a bug in the input data, but _could_ be a bug in msgspec itself. If you could provide some example data that leads to this issue I'd be happy to take a look.

**Comment by jose-gomez-evinex** [comment]
Thank you for the quick response!

At this moment I can't share the .json (sensitive) data but the json is well formatted (tested in several dev. enviroments).

I think the problem resides in the hosting limits. But not sure how to handle the request in this case.

What I think it's happening is that the .json file is not being completely read so ```data``` is incomplete.

I know this may fall outside msgspec but here's Heroku's information regarding http requests:

https://devcenter.heroku.com/articles/http-routing#request-buffering

**Comment by jcrist** [comment]
> What I think it's happening is that the .json file is not being completely read so data is incomplete.

IIUC this just has to do with how data is processed out; nothing here should result in a truncated response.

---

Thinking on this a bit, is there a chance `.content` isn't utf-8 encoded? `msgspec` only works on utf-8 data if handed a `bytes` object. IIRC you can check this with `response.encoding`/`response.apparent_encoding`. If those aren't utf-8, then that's likely the source of the errors. In that case, you could:

- Use `response.text` instead of `response.content`. This will pay an extra unicode encoding/decoding cost, but should work for any text encoding.
- If you control the server side as well, possibly modify the return encoding to ensure the results are utf-8.

**Comment by jose-gomez-evinex** [comment]
Both `encoding` and `apparent_encoding` are `utf-8`

Also here's the response.headers:

```json5
{
'Date': 'Mon, 10 Apr 2023 19:10:54 GMT',
'Server': 'Apache',
'Last-Modified': 'Mon, 10 Apr 2023 19:05:37 GMT',
'Accept-Ranges': 'bytes',
'Content-Length': '46099566',
'Keep-Alive': 'timeout=5, max=100',
'Connection': 'Keep-Alive',
'Content-Type': 'application/json'
}
```

Using `response.text` fixes this issue!

I'll use response.text from now but I was wondering if you have any hint, best-practice or advice to make this better?

I can control the server side.

Thank you so much for your assistance.

**Comment by jcrist** [comment]
Hmmm, reading the requests codebase, it looks like `.text` can still ignore the content encoding on some errors. It also uses `errors="replace"` to handle any unicode decoding errors (signalling the input data isn't really utf-8).

See these lines here:

https://github.com/psf/requests/blob/7f694b79e114c06fac5ec06019cada5a61e5570f/requests/models.py#L931-L942

Can you try manually walking through those lines to see if you're hitting the fallback case? Specifically I'm curious about the following:

```python
str(response.content, "utf-8", errors="replace")  # does this error?

str(response.content, "utf-8")  # and does this error?
```

**Comment by jcrist** [comment]
Closing as stale, please reply/reopen if your issue persists. Closing.
