### ISSUE TITLE
__setattr__ of inherited class is not called

### ISSUE THREAD

**Issue by glebarez** [jcrist/msgspec#374]
### Description

Our business logic requires to log struct attribute access (read/write).
This is currently not working with ```msgspec```. Can you guide here, please?

```python
import msgspec
from typing import Any


class MySub(msgspec.Struct):
    x: int

    def __getattribute__(self, name: str):
        print("reading %s" % name)
        return super().__getattribute__(name)

    def __setattr__(self, name: str, value: Any) -> None:
        print("setting %s" % name)
        return super().__setattr__(name, value)


if __name__ == "__main__":
    s = MySub(x=0)
    _ = s.x  # __getattribute__ is called, OK
    s.x = 1  # no calling of __setattr__ here
```

Result:
```console
reading x
```

Expected result:
```console
reading x
setting x
```

PS: this is possible in Pydantic

**Comment by jcrist** [comment]
Thanks for opening this, looks like you found a bug! This is fixed in #376.

Until we cut a release, you can [install from GitHub](https://jcristharif.com/msgspec/install.html#installing-from-github).
