### ISSUE TITLE
[Question] how to recursively deserialize/decode

### ISSUE THREAD

**Issue by spacemanspiff2007** [jcrist/msgspec#375]
I am currently thinking about using msgspec to use as a web socket deserializer for HABApp.
However the openHAB project uses an unconventional [json-in-json](https://www.openhab.org/docs/configuration/websocket.html#receiving-events-openhab-client) approach (see `payload` field).
I tried modeling it accordingly but obviously I'm getting an error:

````python
import msgspec


class ItemStateEvent(msgspec.Struct):
    type: str
    value: str


class BaseMsg(msgspec.Struct):
    type: str
    topic: str
    payload: ItemStateEvent


input = "{\"type\":\"ItemStateEvent\"," \
        "\"topic\":\"openhab/items/DTR/state\"," \
        "\"payload\":\"{\\\"type\\\":\\\"Quantity\\\",\\\"value\\\":\\\"5MB/s\\\"}\"}"


decoder = msgspec.json.Decoder(BaseMsg)
ret = decoder.decode(input)
````
````
msgspec.ValidationError: Expected `object`, got `str` - at `$.payload
````

Is there any way how I can indicate that the payload field shall be deserialized after/during the BaseMsg deserialization?

**Comment by AlexanderMartynoff** [comment]
In you `input` you have `payload` key with string value, because it in double quotes. Just remove double quotes for `payload`

**Comment by spacemanspiff2007** [comment]
But `input` is how I would receive the data from the openHAB application which means it's not possible to edit the data by hand.

So I'm wondering if there is any way to indicate that the value of `payload` is a json string which should be deserialized, too.

**Comment by AlexanderMartynoff** [comment]
In that case I would try customization decoding with this - https://jcristharif.com/msgspec/extending.html?

**Comment by spacemanspiff2007** [comment]
> Hi, apologies for the delayed reply here.

No worries - you made it worth the wait with your detailed answer with a working example.
Thank you very much for that!

I tried playing around with the `dec_hook`, too.
From the docs I would have expected something like this to work
````python
import msgspec


class ItemStateEvent(msgspec.Struct):
    type: str
    value: str


class BaseMsg(msgspec.Struct):
    type: str
    topic: str
    payload: ItemStateEvent


def dec_hook(type, value):
    if type is ItemStateEvent:
        return ItemStateEvent(msgspec.json.decode(value, type=ItemStateEvent))
    raise TypeError(f"{type} is not supported")


decoder = msgspec.json.Decoder(BaseMsg, dec_hook=dec_hook)

msg = (
    '{"type":"ItemStateEvent","topic":"openhab/items/DTR/state",'
    '"payload":"{\\"type\\":\\"Quantity\\",\\"value\\":\\"5MB/s\\"}"}'
)

res = decoder.decode(msg)
print(res)


````
however this again raises the exception
````
msgspec.ValidationError: Expected `object`, got `str` - at `$.payload`
````

---

The solution you proposed unfortunately does not work for me:
Now the type of payload is of `JSONStr` and the type checks in the IDE (etc.) are not working any more:
![grafik](https://user-images.githubusercontent.com/10754716/234172266-95b747d6-6592-4dd1-a8da-6e86dfbba7e6.png)
Since there are lots of different kinds of messages using the .value doesn't provide much benefit since I would have to narrow the type based on the type field of the base msg.
Maybe I should have made that more clear - sorry.

Do you have any more ideas?
It would have been really nice if there would have been a way to indicate to deserialize the `payload` field on the model because I could have used tagged unions since the type information is in `msg.type`, e.g.

````python
class ItemStateEventPayload(msgspec.Struct, tag=False):
    type: str
    value: str


class ItemStateEventMsg(msgspec.Struct, tag='ItemStateEvent'):
    topic: str
    payload: ItemStateEventPayload

class AnotherMsg(msgspec.Struct, tag='AnotherMsg'):
    ...

class AThirdMsg(msgspec.Struct, tag='AnotherMsg'):
    ...

decoder = msgspec.json.Decoder(ItemStateEventMsg | AnotherMsg | AThirdMsg)

msg = (
    '{"type":"ItemStateEvent","topic":"openhab/items/DTR/state",'
    '"payload":"{\\"type\\":\\"Quantity\\",\\"value\\":\\"5MB/s\\"}"}'
)

res = decoder.decode(msg)
print(res)
````

That way I could have have the whole deserialisation logic offloaded onto msgspec which I hoped would be much faster and less error prone than my python code.

**Comment by jcrist** [comment]
Closing as stale/resolved. Please comment/open a new issue if you have more questions.
