### ISSUE TITLE
Support tagged unions for nested classes

### ISSUE THREAD

**Issue by lfgraphika** [jcrist/msgspec#395]
### Description

Hello. Love this library. Thank you.

I am currently making use of nested classes in a project. Something like this:

```python

class Node(msgspec.Struct):
    ...

class Tree:
    class Root(Node):
       ...
        class Branch(Node):
            ...
            class Leaf(Node):
                ...
```

I would like to tag the subclasses of `Node` but only the classname is passed to the `tag` function. E.g.,

```python
def get_tag(x):
    print(x)
    return x

class Node(msgspec.Struct, tag=get_tag):
    ...

class Tree:
    class Root(Node):
       ...
        class Branch(Node):
            ...
            class Leaf(Node):
                ...

# output:
# Node
# Root
# Branch
# Leaf
```

Ideally, I'd like to have tag values that look like this:

```
Node
Root
Root.Branch
Root.Branch.Leaf
```

I could handle that on my own if the callback were provided with the class object itself instead of the class name as a string. With the current API, I don't think it's possible to use nested classes and guarantee a unique tag value.

Any thoughts are appreciated.

**Comment by jcrist** [comment]
Thanks for opening this, this has been fixed in #399. We now use a variant of a type's `__qualname__` instead of its `__name__` (specifically we use the `__qualname__`, but with any namespace prefixes from nested functions stripped out). For non-nested classes the behavior is the same as before, but for nested classes the default is now what you want above:

```python
import msgspec


class Node(msgspec.Struct, tag=True):
    pass


class Tree(Node):
    class Root(Node):
        class Branch(Node):
            class Leaf(Node):
                pass


print(msgspec.json.encode(Tree.Root.Branch.Leaf()))
# > b'{"type":"Tree.Root.Branch.Leaf"}'
```

**Comment by lfgraphika** [comment]
This is great! Thank you! Is there a regular release schedule or when might we see this in a package release?

**Comment by jcrist** [comment]
Apologies for the delayed response here - 0.15.0 has been released with this feature.
