### ISSUE TITLE
Are msgspec Encoder/Decoder's methods thread-safe?

### ISSUE THREAD

**Issue by sirfz** [jcrist/msgspec#401]
### Description

It's not stated anywhere in the documentation so I'm asking here and hope it can be explicitly added to the documentation. Can we call `encode` or `decode` of the same encoder/decoder from multiple threads?

**Comment by jcrist** [comment]
Thanks for opening this, and apologies for the delayed response here - we're in the middle of a cross-country move.

Previously all top-level functions (`msgspec.json.encode`/`msgspec.json.decode`/...) were threadsafe, but methods on `Encoder`/`Decoder` instances were not. This was a known (but undocumented) deficiency, but was something I had been putting off fixing for now. In #402 I've resolved this - now all functionality in `msgspec` should be threadsafe.

I expect to cut a release sometime in the next week, but if you want to try things out before then you can [install from GitHub](https://jcristharif.com/msgspec/install.html#installing-from-github).

**Comment by sirfz** [comment]
Thank you for addressing this, I will upgrade some time once the new version is released and let you know if any problems persist.

Would be great if you can explicitly mention thread-safety in the documentation as well 🙏
