### ISSUE TITLE
Add a to specify fields which should not be serialized

### ISSUE THREAD

**Issue by saolof** [jcrist/msgspec#407]
### Description

It would be nice to specify fields which msgspec should not include when serializing, such as private fields/caches in python or passwords. Pydantic lets you specify this using exclude.

**Comment by jcrist** [comment]
Would #199 satisfy your needs? This wouldn't allow for dynamically deciding what fields are serialized/deserialized (as pydantic's `exclude` allows), but would allow statically omitting certain fields from the message structure.

**Comment by saolof** [comment]
Ah yes - treat this as a duplicate issue, sorry
