### ISSUE TITLE
decode not returning datetime object as datetime but as str

### ISSUE THREAD

**Issue by nandish486** [jcrist/msgspec#413]
### Description

![image](https://github.com/jcrist/msgspec/assets/93249676/d55eb7e6-cca2-454a-8bff-89a3c4d274ca)
when we encode it to str, it must save as $date or anything,

and when we decode it it must return class datetime.datetime, but it is string, how to fix

**Comment by jcrist** [comment]
See this section of the docs: https://jcristharif.com/msgspec/supported-types.html#any

> When decoding a message with Any type (or no type specified), encoded types map to Python types in a protocol specific manner.

To decode a message into an alternate type (validating the message along the way), you need to specify the expected type via the `type` parameter.

```python
import msgspec
from datetime import datetime

a = {"dada": datetime.now()}

a = msgspec.json.encode(a)
print(a)
#> b'{"dada":"2023-05-23T00:11:53.993027"}'


class Example(msgspec.Struct):
    dada: datetime


b = msgspec.json.decode(a, type=Example)
print(b)
#> Example(dada=datetime.datetime(2023, 5, 23, 0, 11, 53, 993027))
```
