### ISSUE TITLE
TypeError with Decoder as a generic function argument

### ISSUE THREAD

**Issue by koioannis** [jcrist/msgspec#414]
### Description

I am trying to pass a decoder as an argument in a function. Here's a simplified version of the code I'm attempting:
```python
from typing import TypeVar
import msgspec

T = TypeVar("T")

datab = b'{"baz": "baz"}'


class Foo(msgspec.Struct):
    baz: str


def get_foo(decoder: msgspec.json.Decoder[T], datab: bytes) -> T:
    return decoder.decode(datab)


decoder = msgspec.json.Decoder(Foo)
val = get_foo(decoder, datab)
```

However, the above code results to this error:

```error
Traceback (most recent call last):
  File "/path/to/file.py", line 13, in <module>
    def get_foo(decoder: msgspec.json.Decoder[T], datab: bytes) -> T:
TypeError: 'type' object is not subscriptable
```

Here's a similar example using only Python that functions as expected:

```python
from typing import Generic, TypeVar

T = TypeVar("T")


class Bar(Generic[T]):
    def __init__(self, value: T) -> None:
        self._value = value

    @property
    def value(self) -> T:
        return self._value


def get_value(bar: Bar[T]) -> T:
    return bar.value


value = get_value(Bar[int](10)) # get's correctly type hinted
```

I'm unsure if this is an actual bug or if it's expected behavior. Any clarification on this would be appreciated.

P.S. Thanks for developing such an excellent package!

**Comment by jcrist** [comment]
Thanks for opening this issue, this should be resolved by #415. With that PR, `Decoder` types may be successfully parametrized at runtime for any version of python >= 3.9. I have confirmed that your above script runs fine with this PR.

Alternatively, you can enable `__future__.annotations`. to delay evaluation of type annotations, which would avoid the issue altogether. This runs fine even without #415, and would work on Python >= 3.8.

```python
from __future__ import annotations

from typing import TypeVar
import msgspec

T = TypeVar("T")

datab = b'{"baz": "baz"}'


class Foo(msgspec.Struct):
    baz: str


def get_foo(decoder: msgspec.json.Decoder[T], datab: bytes) -> T:
    return decoder.decode(datab)


decoder = msgspec.json.Decoder(Foo)
val = get_foo(decoder, datab)
```
