### ISSUE TITLE
Question: struct for keyless array at root

### ISSUE THREAD

**Issue by tunecrew** [jcrist/msgspec#430]
### Description

We are using structs in order to identify, validate, and parse a variety of JSON data we receive from third parties in our application.

Sometimes this takes the form of a keyless array at the root, i.e.
```
[
  {"key": "value", ...},
  {"key": "value", ...},
  ...
]
```

Is there a way to have an anonymous list at the root of a struct in order to accommodate this?

Something like:
```
class MyJsonData(msgspec.struct):
  _root: list[MyObject]
```

Thanks

**Comment by provinzkraut** [comment]
Does it specifically need to be a `Struct`?

You can achieve this without one:

```python
msgspec.json.decode(data, type=list[MyObject])
```
