### ISSUE TITLE
Nested array_like=True

### ISSUE THREAD

**Issue by ahopkins** [jcrist/msgspec#432]
### Description

It seems that nested `array_like=True` is not working as expected.

Here's the scenario:

```python
from msgspec import Struct
from msgspec.json import decode


class Point(Struct, array_like=True):
    lng: float
    lat: float


class Shape(Struct, array_like=True):
    points: list[Point]


single_point_data = b"[10,20]"
multiple_points = b"[[10,20],[30,40],[50,60]]"

single = decode(single_point_data, type=Point)  # << This is OK
print(single)

multiple = decode(multiple_points, type=Shape)  # << This fails ValidationError
print(multiple)
```

The output I receive:

```
Point(lng=10.0, lat=20.0)
Traceback (most recent call last):
  File "/tmp/p.py", line 19, in <module>
    multiple = decode(multiple_points, type=Shape)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `array`, got `int` - at `$[0][0]`
```

As you can see, the `Point` is fine, but the list of points is not.

**Comment by ahopkins** [comment]
To work around this:

```python
multiple = Shape([Point(*data) for data in decode(multiple_points)])
```

But, this seems like something that I should not have to do.

**Comment by ahopkins** [comment]
Ahh, I see. Thanks so much for the quick response.

**Comment by jcrist** [comment]
No worries, and thanks for the kind words! Please let me know if you run into any further questions or issues.

**Comment by ahopkins** [comment]
@jcrist :laughing: Just realized you posted on this PR: https://github.com/sanic-org/sanic-ext/pull/197

Thanks. I feel like the ability of not only handling the modeling, but also the deserialization calls for a deeper integration, but I'm still working out in my head how to accomplish that.
