### ISSUE TITLE
Validation fails on an optional property in a Struct

### ISSUE THREAD

**Issue by yqiang** [jcrist/msgspec#433]
### Description

First, thanks for the amazing work on this project. It's a real joy to use :) 

I have the following struct declaration, which is part of a more complex struct that I'm trying to decode:
```
class ServingForExport(msgspec.Struct, kw_only=True):
    id: UUID
    description: str
    nutrition_multiplier: float
    nutrition_panel_id: UUID
    measure: str | None
    amount: float | None
    metric_unit: str | None
    metric_value: float | None
    log_count: int = 0
    sort_order: int = 0

    derived_from: UUID | None 
    is_public: bool = True

    def to_dict(self):
        return {f: getattr(self, f) for f in self.__struct_fields__}
```

Notice that I've declared `derived_from` as an optional UUID (or at least, that's what I think the syntax does). When I try to decode json that is missing this field, I get the following error:

```
msgspec.ValidationError: Object missing required field `derived_from` - at `$.hits[0].document.servings[0]`
```

I can work around this by providing a default value of `None`, but I'd rather that the property not be included at all if it's missing.

Am I misunderstanding how optional properties work?

**Comment by jcrist** [comment]
> Am I misunderstanding how optional properties work?

Yes. Only fields with default values aren't required, all other fields are required. The "optional" in `typing.Optional` is a bit of a misnomer, as it doesn't really mean a field is optional (we follow dataclass semantics here, matching python's builtin behavior). As you've noted, if you change it to:

```python
    ...
    derived_from: UUID | None = None
    ...
```

then `derived_from` will default to `None` if it's not found in the message.

> I can work around this by providing a default value of None, but I'd rather that the property not be included at all if it's missing.

What do you mean by "not included at all" here? Structs aren't dicts - a struct must always have values set for all fields defined.

Guessing what you might mean by this, here's two docs sections that might interest you:

- Using the [`UNSET` singleton](https://jcristharif.com/msgspec/supported-types.html#unset) for representing "unset" fields in object types (structs, dataclasses, attrs, etc...)
- [Omitting default values](https://jcristharif.com/msgspec/structs.html#omitting-default-values) for excluding fields containing their default values during encoding

Does that answer your question?

**Comment by jcrist** [comment]
```python
    def to_dict(self):
        return {f: getattr(self, f) for f in self.__struct_fields__}
```

Also, note that you can use [`msgspec.structs.asdict`](https://jcristharif.com/msgspec/api.html#msgspec.structs.asdict) instead of this helper, which should provide a mild speedup.

**Comment by yqiang** [comment]
Thanks for the quick reply. Omitting default values is exactly what I was looking for. Also, thanks for the pointer to asdict, it'll do exactly what I need it to do.

**Comment by mullenkamp** [comment]
> > Am I misunderstanding how optional properties work?
> 
> Yes. Only fields with default values aren't required, all other fields are required. The "optional" in `typing.Optional` is a bit of a misnomer, as it doesn't really mean a field is optional (we follow dataclass semantics here, matching python's builtin behavior). As you've noted, if you change it to:
> 
> ```python
>     ...
>     derived_from: UUID | None = None
>     ...
> ```
> 
> then `derived_from` will default to `None` if it's not found in the message.
> 
> > I can work around this by providing a default value of None, but I'd rather that the property not be included at all if it's missing.
> 
> What do you mean by "not included at all" here? Structs aren't dicts - a struct must always have values set for all fields defined.
> 
> Guessing what you might mean by this, here's two docs sections that might interest you:
> 
>     * Using the [`UNSET` singleton](https://jcristharif.com/msgspec/supported-types.html#unset) for representing "unset" fields in object types (structs, dataclasses, attrs, etc...)
> 
>     * [Omitting default values](https://jcristharif.com/msgspec/structs.html#omitting-default-values) for excluding fields containing their default values during encoding
> 
> 
> Does that answer your question?

Hi @jcrist ,

It took me a while to find this. I was wondering if you can add this bit of info on the documentation site? It's currently not clear that Optional isn't really optional, but another way of adding None as an option. 
I'm guessing there isn't actually a way to not assign a default value and truly have a field as optional?

Thanks,
Mike

**Comment by jack-mcivor** [comment]
@mullenkamp this really is a misnomer in all of Python. From https://docs.python.org/3/library/typing.html#typing.Optional:
> Optional[X] is equivalent to X | None (or Union[X, None]).
> Note that this is not the same concept as an optional argument, which is one that has a default. 

I think pretty much everyone agrees it's clearer to use `X | None` in Python 3.10+. There are tools that will actually do this for you automatically - eg. https://github.com/asottile/pyupgrade?tab=readme-ov-file#pep-604-typing-rewrites

**Comment by mullenkamp** [comment]
Hi @jack-mcivor ,

Thanks for that. I guess I never got my head around what Optional really means. It's funny that they even have a tool to convert Optional to the newer syntax.
