### ISSUE TITLE
Option to JSON encode Decimal types as numbers, not strings

### ISSUE THREAD

**Issue by jcrist** [jcrist/msgspec#440]
> We like that msgspec handles decimal however they are embedded as strings. Here is some finding from another discussion around handling decimals.

> https://github.com/meltano/sdk/issues/1046#issuecomment-1535493163

> Do we think that msgspec might output decimals like simplejson without the double quotes in the future?

_Originally posted by @s7clarke10 in https://github.com/jcrist/msgspec/issues/349#issuecomment-1586444502_

**Comment by jcrist** [comment]
In the future I'd expect to make the encoding of `Decimal` types configurable, but currently that's not possible. However, I'd argue that encoding `Decimal` types as strings is the optimal format, and would encourage you to rethink using numbers for these objects.

Encoding decimals as strings makes it easier for downstream consumers of the JSON to properly load decimal objects without losing precision. Most JSON libraries (both in Python and in other languages) don't support hooking into the parsing process for numbers (`123`, `123.45`, ...) - they almost always get converted to a `float64` before being passed off to downstream code. This means that encoding decimals as numbers would prevent most libraries from reading this data with full precision.

For example, using `JSON.parse` in javascript, then converting the output into a decimal from [`decimal.js`](https://mikemcl.github.io/decimal.js/) only accurately roundtrips the decimals if they're serialized as JSON strings, not JSON numbers. This is because there's no way to grab the string representation of the number before it's parsed into a float64 (where it loses precision). You can see this in [this JSFiddle](https://jsfiddle.net/ebhkp7d0/).

**Comment by s7clarke10** [comment]
Brilliant, thank you for looking into the use case for this and raising a new issue.

I agree with you that outputting as a string can avoid downstream issues including truncation, we have certainly seen this issue. In some situations we wish to treat decimals as decimals, so the option to make this configurable sounds like a good path forward. Thank you for you efforts in producing this package.
