### ISSUE TITLE
enc_hook for subclasses of tuple/NamedTuple not working?

### ISSUE THREAD

**Issue by dmtvanzanten** [jcrist/msgspec#441]
### Description

Hi, thank you for your amazing work!
I'm trying to use an enc_hook to control the serialization of a subclass of tuple/NamedTuple, but it seems that the enc_hook is never called (it does get called for subclasses of int & str). 

Please consider the following code snippet. 
```python 

def enc_hook(obj):
    print(f"{obj} triggered this enc_hook call")
    if isinstance(obj, MyTuple):
        return tuple(obj)
    elif isinstance(obj, int):
        return int(obj)
    raise TypeError(f"Type {type(obj)!r} is unsupported")


class MyTuple(tuple):
    pass

class MyInt(int):
    pass

encoder = msgpack.Encoder(enc_hook=enc_hook)

encoder.encode([MyInt(0), MyInt(0)])
encoder.encode([MyTuple(['Hello']), MyTuple(['World'])])
```

This outputs:
```python
0 triggered this enc_hook call
0 triggered this enc_hook call
```

My expectation is that I would see:
```python
0 triggered this enc_hook call
0 triggered this enc_hook call
Hello triggered this enc_hook call
World triggered this enc_hook call
```

Is my understand correct, and if so how would I be able to adjust the serialization of tuple/NameTuple subclasses.

**Comment by jcrist** [comment]
The current architecture of msgspec doesn't allow for adjusting the serialization format of natively supported types. Since subclasses of `tuple` (and `NamedTuple`) are handled natively by msgspec, you cannot customize how they're serialized in `enc_hook`.

This architectural limitation is why we've been reluctant to natively support some types, since native support currently means users cannot change how they're serialized. We currently only natively support encoding subclasses of collection types (`list`, `tuple`, ...) but not subclasses of scalar types (`int`, `str`, ...) - the assumption being that collection types almost always should serialize the same as their base class. I can't think of a time where I've ever wanted to serialize a list differently, but can think of times where `int` subclasses should be treated differently.

Can you say more about your use case? How do you want your `tuple` subclasses to be serialized and why?

**Comment by dmtvanzanten** [comment]
I would like to have an immutable that is callable to represent simple stand-alone functions. 
The immutable class implements a classmethod to be used as a decorator on simple functions. This decorator would inspect the wrapped function (and e.g. raise errors if the function uses globals etc), derive some information (including the functions source code, packages used), and create an instance of my immutable class (in my case a NamedTuple) which implements the __call__ dunder to call the 'original' function (it is actually a reconstructed version of the original function).

I would like this instance to be a subclass of an immutable such that none of the information stored in the class instance can ever be adjusted (I understood, one can always change the data in dataclasses, even when using frozen=True). 

But when serialising the instance, I only need a sunset of the info of the immutable subclass instance (for example, I don't need the actual functiontype object because I have the source code, incl reference to external packages etc).

I agree that this is perhaps a corner case, but it would be amazing if possible.
Thank you for your quick reply btw.

**Comment by jcrist** [comment]
> I would like this instance to be a subclass of an immutable such that none of the information stored in the class instance can ever be adjusted (I understood, one can always change the data in dataclasses, even when using frozen=True).

In python anything can be made mutable with enough hackery, tuples included. A frozen dataclass (or a frozen `msgspec.Struct` type) is immutable enough to prevent accidental mutation - a user determined to mutate a thing in python can always find a way to intentionally mutate something.

In your case it sounds like your actual use case is "how can I avoid serializing some of the state on an object". This is an instance of #199. We're not quite there yet, but I'd expect that issue to be resolved as part of the next major release.

In the meantime you can hack around this issue by storing the state you don't want to be serialized in an undeclared field on the `__dict__` of  a frozen `msgspec.Struct` (see [here](https://jcristharif.com/msgspec/api.html#msgspec.Struct) and [here](https://jcristharif.com/msgspec/structs.html) for more info). I'm not sure what information you'd want to store on your object, but hopefully this example gets you started:

```python
from __future__ import annotations
import importlib

import msgspec


# Set `frozen=True` to disable `__setattr__` on the struct,
# and `dict=True` to support storing undeclared attributes on the instance
class Function(msgspec.Struct, frozen=True, dict=True):
    # This implementation serializes a callable by module import path and qualname
    module: str
    qualname: str

    @classmethod
    def wrap(cls, func) -> Function:
        out = cls(func.__module__, func.__qualname__)
        # Store the function in a hidden private attribute
        out.__dict__["_func"] = func
        return out

    def __call__(self, *args, **kwargs):
        if not hasattr(self, "_func"):
            # `_func` hasn't been loaded yet on this instance, import it and stash it
            obj = importlib.import_module(self.module)
            for name in self.qualname.split("."):
                obj = getattr(obj, name)
            self.__dict__["_func"] = obj
        return self._func(*args, **kwargs)


@Function.wrap
def add(x, y):
    return x + y


print(f"add(1, 2) = {add(1, 2)}")
#> add(1, 2) = 3

serialized = msgspec.json.encode(add)
print(serialized)
#> b'{"module":"__main__","qualname":"add"}'

add2 = msgspec.json.decode(serialized, type=Function)
print(f"add2(1, 2) = {add2(1, 2)}")
#> add2(1, 2) = 3
```
