### ISSUE TITLE
Post-init hook

### ISSUE THREAD

**Issue by akotlar** [jcrist/msgspec#442]
### Description

One of the features that allows for easy runtime validation in dataclasses.dataclass is the post init hook. By providing an opt-in option for Structs, most use cases for libraries like attrs / dataclass could be entirely replaced, and presumably with better performance.

This could be done as a reserved \__post_init__ as on data class, or following attrs, \__msgspec_post_init__. By default this method simply returns (and could probably be elided entirely), should not cost much performance.

### Example
Currently we (Bystro team) use Struct for serialization/deserialization (and the validation at the IO boundary that this enables), but need attrs to enable runtime validation, for instance https://github.com/bystrogenomics/bystro/blob/4dfdeee8c592a69f840013ea95cfd12a5fc3ae99/python/python/bystro/ancestry/ancestry_types.py#L137.
- It would be possible for us to wrap Struct in a custom class that carries this post init hook, but that is somewhat less ergonomic.
- In most, but I don't think all cases, it would be possible to do the validation as a dec_hook. Similarly, for enc_hook
  - For instance json -> Obj1 -> {Obj2 -> model1, Obj3 -> model2} -> Result -> json, where we want to validate Obj2 and Result. Obj2 and Obj3 may be derived from Obj1, but need to validate the content of the values, not just the types. It would be  awkward to require the dec_hook for Obj1 to have knowledge of Obj2 and Obj3.
- We could also continue to use Struct + attrs, but there is nothing I want in attrs besides post-init validation and requiring a 2nd library just for that feature is heavy.

You've put a whole lot of thought into this library, and it may be that you already have a mechanism for handling this, I would welcome feedback. I really love what you've done here, and see Struct as the container that I want to use for all of my data modeling needs.

Thanks very much for considering!

**Comment by jcrist** [comment]
Thanks for opening this issue, a `__post_init__` hook for struct types is definitely in scope for `msgspec`. In the long run I plan to add a more explicit custom validation mechanism that might be a better spot to put the behavior you're handling in `__attrs_post_init__`, but in the short term handling it in `__post_init__` seems fine to me.

>  it may be that you already have a mechanism for handling this

We don't currently have a mechanism for handling custom behavior that should run on `__init__` as well as `decode`. If you have behavior you only want to run on `__init__` (and not `decode`) then the generally recommended pattern is to define an alternative `classmethod` constructor like:

```python
class Example(msgspec.Struct):
    x: int
    y: int

    @classmethod
    def create(cls, x: int, y: int) -> Example:
        return cls(abs(x), abs(y))  # standin for some custom behavior

Example.create(1, -1)  
```

This matches the recommendations from attrs as well (see [the attrs docs here]( https://www.attrs.org/en/stable/init.html)).

Looking at your use case though, I _think_ you want the custom code to also run on `decode`, so this recommendation likely doesn't apply.

**Comment by akotlar** [comment]
Thank you very much for the feedback and the implementation. You rock, sir.
