### ISSUE TITLE
`defstruct` not accepting `None` as a value for `module` and `namespace` parameters

### ISSUE THREAD

**Issue by provinzkraut** [jcrist/msgspec#444]
### Description

Passing `module=None` or `namespace=None` to `defstruct` results in a `TypeError`, despite these values being typed as accepting `None`.

```python
from msgspec import defstruct

defstruct(name="foo", fields=(), module=None)
# TypeError: defstruct() argument 4 must be str, not None
```

```python
from msgspec import defstruct

defstruct(name="foo", fields=(), namespace=None)
# TypeError: defstruct() argument 5 must be dict, not None
```

<hr>

This is quite impractical when you need to conditionally pass a module or namespace, since it leaves you with code like this:

```python
kwargs = {"name": "foo", ...}
if module_name:
  kwargs["module"] = module_name
struct = defstruct(**kwargs)
```

or if you still want to type check the call:

```python
if module name:
 struct = defstruct(name="foo", module=module_name)
else:
 struct = defstruct(name="foo")
``` 

which isn't too bad with just two args, but for a larger number isn't that ideal.

<hr>

The question is whether the documentation, type annotation or implementation is wrong, since they all state different things.

**Comment by jcrist** [comment]
Thanks for reporting this, this should be fixed by #445. `module`, `namespace` (and also `bases`) now all accept `None` as an argument.

> The question is whether the documentation, type annotation or implementation is wrong, since they all state different things.

Apologies, I might be misinterpreting this sentence - are you saying there was also a discrepancy between the docs and the type annotations (rather than between the docs/annotations and the implementation)? If so, can you clarify what that discrepancy was?

**Comment by provinzkraut** [comment]
Thanks for the quick fix @jcrist!

> Apologies, I might be misinterpreting this sentence - are you saying there was also a discrepancy between the docs and the type annotations

Sorry for the missing specificity! What I meant was that it wasn't obvious to me which part was wrong. I initially encountered this behaviour and it was surprising to me, as the type annotations clearly didn't match with the implementation, so I consulted the docs which describe e.g. `module` as `(str, optional)`, and I thought this *might* mean that a value is not required, but not that it can be `None` if given.

So there was a bit of ambiguity given the behaviour at the time, but the ambiguous reading of the docs would be fairly uncommon and with the implementation now matching the type annotations, I think everything is as expected.

**Comment by peterschutt** [comment]
Confirmed fixed for `module`, thanks!
