### ISSUE TITLE
Support float -> datetime

### ISSUE THREAD

**Issue by peterschutt** [jcrist/msgspec#448]
### Description

Stdlib `datetime` has `fromtimestamp()` and `utcfromtimestamp()` methods. Would you consider supporting `float` values for `datetime` annotated fields?

```python-console
>>> import msgspec
>>> from datetime import datetime
>>> class S(msgspec.Struct):
...   dt: datetime
... 
>>> msgspec.json.decode(b'{"dt":1687335122.596625}', type=S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
msgspec.ValidationError: Expected `datetime`, got `float` - at `$.dt`
```

**Comment by jcrist** [comment]
Sure, I think this makes sense. A few notes on how I'd implement this:

- This conversion path would only be supported for [`strict=False`](https://jcristharif.com/msgspec/usage.html#strict-vs-lax-mode) decoding/conversion. This means by default this conversion wouldn't be allowed.
- If `strict=False`, we'd interpret either `int` or `float` inputs to a `datetime.datetime` fields as seconds since the unix epoch. Pydantic will also implicitly assume a numeric input to a datetime is milliseconds since the epoch if it's big enough, but that seems too squishy for my liking.
- The decoded datetimes would be naive (no timezone attached). Epoch time is usually UTC so I could see an argument that these should be treated as UTC, but other tools in the space don't make this assumption and I think ecosystem consistency is a stronger argument.

If these constraints make sense to you, then I'd be happy to add support for this. Should be fairly straightforward to implement.

**Comment by provinzkraut** [comment]
> If these constraints make sense to you

They do indeed, yes. We use `strict=False` for the validation in any case, so that's not an issue, and the rest sound good as well.

**Comment by peterschutt** [comment]
Thanks @jcrist!

> that seems too squishy for my liking

I can see your point, especially making runtime inference for every conversion does seem a bit over-the-top. Could the unit of the number (e.g, s/ms/ns) be configurable if there happened to be demand for it down the track?

Also, what are your thoughts on supporting same for `datetime.date` and `datetime.time`?

**Comment by jcrist** [comment]
> Could the unit of the number (e.g, s/ms/ns) be configurable if there happened to be demand for it down the track?

If needed later on, then yes this could probably be supported. I'd rather not for now though.

> Also, what are your thoughts on supporting same for datetime.date and datetime.time?

I'm against it unless there's a good reason to. An epoch timestamp is a common format across systems, and describes an instant in UTC time - it maps clearly to a `datetime.datetime` with UTC timezone.

In contrast, a date is not an instant but a range of time (without a timezone), converting from one to the other seems odd and error prone. Do you round to the nearest day in UTC? What systems describe dates in this manner?

Likewise I'm not sure how `float -> time` should be interpreted? What timezone is the output in? How does the input correlate to the time? Total seconds in the day? It feels like a weird and unlikely data format IMO, I'd rather not support it without a real use case.

**Comment by jcrist** [comment]
One open question regarding `float -> datetime` conversion - do we support number-like-strings as inputs as well?

```python
msgspec.convert(1687539329, datetime.datetime, strict=False)  # int input, works
msgspec.convert(1687539329.266808, datetime.datetime, strict=False)  # float input, works
msgspec.convert("1687539329.266808", datetime.datetime, strict=False)  # numeric str input, what should this do?
```

On first pass I'm -0.5 on this, as data coming in as a string already has a natural datetime mapping (following RFC3339). Adding support for numeric strings seems like a potential footgun, as things that look like dates in other less common formats may mistakenly be coerced as epoch timestamps. For example:

```python
# A date as YYYYMMDD
msgspec.convert("20220623", datetime.datetime)  # this will mistakenly be interpreted as an epoch timestamp
```

On the other hand, some formats like querystrings result in only string inputs. Representing a datetime as an epoch timestamp in a querystring isn't uncommon, and forbidding float/int-like-strings -> datetime would make this use case trickier.

**Comment by provinzkraut** [comment]
> Representing a datetime as an epoch timestamp in a querystring isn't uncommon, and forbidding float/int-like-strings -> datetime would make this use case trickier.

This is actually relevant for our use case. We could of course work around this, but it would be easier if it was supported out of the box.

**Comment by peterschutt** [comment]
Thanks @jcrist!

**Comment by jcrist** [comment]
This has been implemented in #452. If you have the time, I'd appreciate if you tried it out before the next release to ensure it solves your use case. See our [instructions here](https://jcristharif.com/msgspec/install.html#installing-from-github) for how to install the development branch from GitHub.

**Comment by peterschutt** [comment]
Will do in the next 24 hours, thanks again.

**Comment by peterschutt** [comment]
> Do you round to the nearest day in UTC?

The reason I brought this up is because the stdlib `datetime` module has `date.fromtimestamp()`:

> Return the local date corresponding to the POSIX timestamp

So it would be the `datetime` truncated to the date, so `2023-12-31T23:59:59Z` would be `2023-12-31`.

Pydantic also supports this.

I also thought it had `time.fromtimestamp()` but looking now, that definitely doesn't exist, so disregard that.

**Comment by peterschutt** [comment]
Can confirm this worked for us, thanks.

**Comment by legout** [comment]
I can confirm that the example from https://github.com/jcrist/msgspec/pull/452#issue-1772433106 works.

However, I´ve got json files with timestamps in milliseconds (e.g. 1654791971000) which results in a `ValidationError: Timestamp is out of range   - at $.timestamp`.  Is there any workaround?
