### ISSUE TITLE
Support for JSON lines (JSON line-delimited)

### ISSUE THREAD

**Issue by naquiroz** [jcrist/msgspec#449]
### Description

It would be nice if the encode could output an array as JSON lines too.

**Comment by jcrist** [comment]
Thanks for opening this, I agree that a method for doing this makes sense. Adding it to the todo list.

**Comment by naquiroz** [comment]
Thank you, any estimate when will this be implemented?

**Comment by jcrist** [comment]
This is done in #479, and will be part of the upcoming release (expect sometime in the next week or so). If you want to try it out before then see our [instructions for installing from GitHub](https://jcristharif.com/msgspec/install.html#installing-from-github).

**Comment by naquiroz** [comment]
Great! I'll wait for the release, because we need it in production, thanks!

> This is done in #479, and will be part of the upcoming release (expect sometime in the next week or so). If you want to try it out before then see our [instructions for installing from GitHub](https://jcristharif.com/msgspec/install.html#installing-from-github).
