### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by KingArrkinian** [jcrist/msgspec#462]
### Description

On calling pip install msgspec, I am getting the error 
`error C2039: 'ob_digit': is not a member of '_longobject'`
with all the versions of msgspec I've tried (0.13, 0.15.1, 0.16.0).

2023-07-03T15:25:18,464   msgspec\_core.c(152): error C2039: 'ob_digit': is not a member of '_longobject'
2023-07-03T15:25:18,464   msgspec\_core.c(159): error C2039: 'ob_digit': is not a member of '_longobject'

I've switched back to 3.11 in the meantime, this is just FYI.

**Comment by jcrist** [comment]
Thanks for opening this, this is a good reminder that we should start testing the 3.12 beta releases (release schedule [here](https://peps.python.org/pep-0693/)). Adding it to the TODO list.

**Comment by jcrist** [comment]
We won't be publishing built packages for python 3.12 until it's actually released, but I fixed the incompatibilities and setup CI to test against 3.12's pre-releases, so the dev branch should at least remain compatible.
