### ISSUE TITLE
Custom Constraints

### ISSUE THREAD

**Issue by illeatmyhat** [jcrist/msgspec#474]
### Description

I'm attempting to parse OpenAPI specs, which have breaking changes between minor versions.
There's a need to disambiguate between different specs even though they're 90% similar.
Therefore, I'd like to do something like
```python
import msgspec
from packaging.version import Version
from packaging.specifiers import SpecifierSet
from msgspec import Struct, Meta
from typing import Annotated, Any, Type

...

class OpenAPI3(Struct):
    openapi: Annotated[Version, Meta(func=lambda x: x in SpecifierSet("~=3.0.0"))]


class OpenAPI3_1(Struct):
    openapi: Annotated[Version, Meta(func=lambda x: x in SpecifierSet("~=3.1.0"))]
```
which should hopefully just give me the the best fitting object instead of a validation error.

**Comment by jcrist** [comment]
The code example you've posted here doesn't appear to be complete, so I'm only guessing at what you're trying to accomplish here. It _sounds_ like you're trying to parse different OpenAPI docs, disambiguating on the `openapi` field.

There are 2 ways you might approach this problem in msgspec today:

## Using Tagged Unions

If you're comfortable enumerating all the supported values for `openapi`, you could handle this using a [Tagged Union](https://jcristharif.com/msgspec/structs.html#tagged-unions). You'd have a fixed schema for `3.0.0` and `3.1.0`, and empty subclasses for each pointer version just to build up the mapping. Something like:

```python
from __future__ import annotations

from typing import Union

import msgspec


class OpenAPI300(msgspec.Struct, tag="3.0.0", tag_field="openapi"):
    # OpenAPI 3.0.* schema here
    ...


class OpenAPI310(msgspec.Struct, tag="3.1.0", tag_field="openapi"):
    # OpenAPI 3.1.* schema here
    ...


# Empty Subclasses to explicitly map known 3.0.* versions to the 3.0.0 schema
class OpenAPI301(OpenAPI300, tag="3.0.1"):
    pass


class OpenAPI302(OpenAPI300, tag="3.0.2"):
    pass


class OpenAPI303(OpenAPI300, tag="3.0.3"):
    pass


decoder = msgspec.json.Decoder(
    Union[OpenAPI300, OpenAPI301, OpenAPI302, OpenAPI303, OpenAPI310]
)


def parse(msg: bytes) -> OpenAPI300 | OpenAPI310:
    return decoder.decode(msg)
```

## Parse `openapi` first, then manually branch on that

You could also first parse out just the `openapi` field, then manually branch on that. This will be slower than explicitly listing all possible values like above, but the performance impact may not matter for your application. Something like:

```python
from __future__ import annotations

import msgspec


class OpenAPI30(msgspec.Struct):
    # OpenAPI 3.0.* schema here
    ...


class OpenAPI31(msgspec.Struct):
    # OpenAPI 3.1.* schema here
    ...


class _Common(msgspec.Struct):
    openapi: str


def parse(msg: bytes) -> OpenAPI30 | OpenAPI31:
    # First parse out just the common `openapi` field
    common = msgspec.json.decode(msg, type=_Common)

    version = tuple(common.openapi.split(".", 2))[:2]

    # Select the proper schema based on the version
    if version == ("3", "1"):
        cls = OpenAPI31
    elif version == ("3", "0"):
        cls = OpenAPI30
    else:
        raise ValueError(f"Unsupported version {common.openapi}")

    # Now reparse with the full schema:
    return msgspec.json.decode(msg, type=cls)
```

**Comment by illeatmyhat** [comment]
Yes, that's exactly what I want to do. The second solution seems good to me.
Performance here is a consideration, but not paramount, since we tend to parse a smaller number of very large specs.

**Comment by jcrist** [comment]
Great, glad to hear it. Since it sounds like you have a solution, I'm going to close this for now. Feel free to reopen or open a new issue if you run into further issues.
