### ISSUE TITLE
Support for loading JSONL (JSON line-limited)

### ISSUE THREAD

**Issue by naquiroz** [jcrist/msgspec#481]
### Description

Since one can now encode into JSONL with #449 , would it be possible to decode JSONL too?

**Comment by jcrist** [comment]
Thanks for opening this, this is definitely something we could support. Should be fairly straightforward to add, tossing it on the todo list.

**Comment by naquiroz** [comment]
Thanks! Will this be in 0.17.1 or 0.18.0?

**Comment by jcrist** [comment]
I'll cut a 0.17.1 at some point in the next week.

**Comment by joao-leme** [comment]
Hey! Any news on this ? 😄
