### ISSUE TITLE
Can msgspec decode NaN?

### ISSUE THREAD

**Issue by TomBurch** [jcrist/msgspec#486]
### Description

`json.dumps` has an optional `allow_nan` which prevents errors when decoding a float with a value of `NaN`

Is there any way of handling this with msgspec?

**Comment by provinzkraut** [comment]
Encoding `NaN` is supported; It will be represented as `null`: https://jcristharif.com/msgspec/supported-types.html#float

**Comment by TomBurch** [comment]
Sorry I meant to say `json.loads` - it natively allows `NaN` and provides `parse_constant` for modifying that behaviour. I'm specifically interested in decoding `NaN` rather than encoding it

**Comment by TomBurch** [comment]
I can see that it works with `"NaN"` in lax mode but I don't think that applies to `NaN`

```
If strict=False is specified, string values may also be coerced to floats. Note that in this case the strings "nan", "inf"/"infinity", "-inf"/"-infinity" (case insensitive) will coerce to nan/inf/-inf. See [“Strict” vs “Lax” Mode](https://jcristharif.com/msgspec/usage.html#strict-vs-lax) for more information.
```

**Comment by provinzkraut** [comment]
So what you're looking for is to decode the string `"NaN"` into `math.nan`?

**Comment by TomBurch** [comment]
I'd like to be able to decode a string like:
```py
b'{"a": NaN, "b": 5}'
```

To be honest I'm not too concerned whether it evaluates as `null` or `nan`

**Comment by provinzkraut** [comment]
Hm. As this is not valid JSON, I don't think msgspec will support this.

Don't take my word for it though since I'm just an avid user. @jcrist probably has to say something more useful about this.

**Comment by TomBurch** [comment]
I agree - and I'd prefer if we weren't generating data like that 😅 
If it's not possible it won't be a huge issue since it's quite an edge case
