### ISSUE TITLE
Extend `Meta` to allow specifying `dec_hook` and `enc_hook`

### ISSUE THREAD

**Issue by Goldziher** [jcrist/msgspec#497]
### Description

Hi @jcrist,

So one use case we now have is to pre-calculate the type decoders and encoders for custom types in advance. I tried to pre-calculate the decoders and encoders and add them as a value inside `Annotated`, but it seems that msgspec strips the `Annotated` and metadata when calling the dec and enc hooks, which sorta makes sense.

I was going to request the metadata is also injected as an optional tuple into the hooks - which would allow me to do all sorts of stuff there, but then it occurred to me it would be even better if I could simply set the dec/enc hooks on the `Meta` instance, which will then instruct msgspec to use these hooks appropriately. 

What do you think?

**Comment by jcrist** [comment]
Apologies for missing this. For decoding this is something I eventually intend to support - the features added in #483 would cover this use case.

Configuration on `Meta` can't work for encoding, as not all values have type information available (for example, there's no annotations available on a top-level list like `[1, 2, 3]`). Encoding works on concrete values, it has no access to abstract types.

Closing in favor of #483.
