### ISSUE TITLE
msgspec.inspect types to python types

### ISSUE THREAD

**Issue by cibere** [jcrist/msgspec#505]
### Description

I would like to suggest a function  which converts the msgspec.inspect types to their python variant.

The reason I want this is because I am trying to put a `msgspec.Struct` subclass in an openapi schema. To tell if a field is required I decided to use the `msgspec.inspect` module, but that returns datatypes in `msgspec.inspect.Type` subclasses, so I'm having to either translate that to their python variant then convert that to the openapi variant (since I already have a func that converts the python variant to openapi variant due to it being needed in other places), or the alternative (purely theoredical) is to interact with `msgspec.inspect._Translator` itself, overriding `msgspec.inspect._Translator._translate_inner` to stop the conversion to the msgspec.inspect types

**Comment by cibere** [comment]
Oh that does work. I guess I was too focused on converting it myself that I didn't think to look for a function which converted the struct for me, thank you!

**Comment by jcrist** [comment]
If you have suggestions for how we could make this more prominent/clear in the docs so users like you can find it, please let me know. Current docs page is here: https://jcristharif.com/msgspec/jsonschema.html
