### ISSUE TITLE
Use the tomllib library for toml if avalible

### ISSUE THREAD

**Issue by cibere** [jcrist/msgspec#506]
### Description

I am using python 3.11 which has a builtin toml parsing library (`tomllib`), yet msgspec wants me to install a different parsing library. ```py
ImportError: `msgspec.toml.encode` requires `tomli_w` be installed.
```
So the feature I'm suggesting is msgspec using the builtin toml lib if available.

**Comment by jcrist** [comment]
`tomllib` doesn't support encoding, only decoding. For decoding we use `tomllib` in python 3.11+, but for encoding we always rely on `tomli_w`.
