### ISSUE TITLE
AttributeError: module 'msgspec' has no attribute 'Struct' on pycharm

### ISSUE THREAD

**Issue by darmahraj** [jcrist/msgspec#509]
### Description

Hi, i tried to run the [query_repodata.py](https://github.com/jcrist/msgspec/blob/main/examples/conda-repodata/query_repodata.py) but seems to hit the Struct error. From previous issue log, found it was fixed in 0.13.0. Tried that version as well as other version (0.16.0 / 0.17.0). Still see the same "Struct" error.

json: 305.69 ms
ujson: 296.70 ms
orjson: 244.16 ms
Traceback (most recent call last):
  File "/Users/draj/PycharmProjects/pythonProject3flogproc/msg_spec.py", line 77, in <module>
    func(data)
  File "/Users/draj/PycharmProjects/pythonProject3flogproc/msg_spec.py", line 15, in query_msgspec
    class Package(msgspec.Struct):
AttributeError: module 'msgspec' has no attribute 'Struct'
simdjson: 134.28 ms

Process finished with exit code 1

**Comment by jcrist** [comment]
> From previous issue log, found it was fixed in 0.13.0.

I'm not sure what issue you're referring to, this has not been an issue in any released version of msgspec.

I suspect the thing you're importing as `msgspec` isn't actually a valid `msgspec` install. This is not a msgspec-specific issue, but something to do with how python's import system works. One possible source of this issue is if you have a file or directory on your python path named `msgspec`.

Can you run the following script from the same working directory that you're running your `msg_spec.py` file?

```python
import msgspec
print(msgspec)
print(dir(msgspec))
```

**Comment by darmahraj** [comment]
Hi jcrist,

Thanks for checking! Its my mistake, renamed the msgspec.py in the same directory. I tried to re-run with the additional you mentioned.

Output
<module 'msgspec' from '/Users/draj/PycharmProjects/pythonProject3flogproc/venv/lib/python3.8/site-packages/msgspec/__init__.py'>
['DecodeError', 'EncodeError', 'Meta', 'MsgspecError', 'NODEFAULT', 'Raw', 'Struct', 'UNSET', 'UnsetType', 'ValidationError', '_Field', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_core', '_json_schema', '_utils', '_version', 'convert', 'defstruct', 'field', 'from_builtins', 'inspect', 'json', 'msgpack', 'structs', 'to_builtins', 'toml', 'yaml']
json: 306.63 ms
ujson: 296.16 ms
orjson: 197.51 ms
simdjson: 121.89 ms
Traceback (most recent call last):
  File "/Users/draj/PycharmProjects/pythonProject3flogproc/msg_spec.py", line 78, in <module>
    func(data)
  File "/Users/draj/PycharmProjects/pythonProject3flogproc/msg_spec.py", line 20, in query_msgspec
    class RepoData(msgspec.Struct):
  File "/Users/draj/PycharmProjects/pythonProject3flogproc/msg_spec.py", line 21, in RepoData
    packages: dict[str, Package]
TypeError: 'type' object is not subscriptable


Also additional changes to the python file i commented the below on all functions

Example: 
def query_msgspec(data: bytes): # -> list[tuple[int, str]]:

**Comment by darmahraj** [comment]
Hi Jcrist, thanks to you i realized my file name being msgpec.py was the issue. I renamed the file i was running from which was msgspec.py to msg_spec.py. 

Unfortunately still noticed this "type" error after that.

```python
Traceback (most recent call last):
  File "/Users/draj/PycharmProjects/pythonProject3flogproc/msg_spec.py", line 13, in <module>
    def query_msgspec(data: bytes) -> list[tuple[int, str]]:
TypeError: 'type' object is not subscriptable
``` 

Then i updated the python library to 3.9. That resolved the issue and i'm able to run the repodata script

Python 3.8 and below doesn't support this syntax
```python
def query_msgspec(data: bytes): -> list[tuple[int, str]]:
``` 

Now running perfectly!
```python
<module 'msgspec' from '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/msgspec/__init__.py'>
['DecodeError', 'EncodeError', 'Meta', 'MsgspecError', 'NODEFAULT', 'Raw', 'Struct', 'UNSET', 'UnsetType', 'ValidationError', '_Field', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_core', '_json_schema', '_utils', '_version', 'convert', 'defstruct', 'field', 'from_builtins', 'inspect', 'json', 'msgpack', 'structs', 'to_builtins', 'toml', 'yaml']
json: 325.11 ms
ujson: 267.99 ms
orjson: 236.25 ms
simdjson: 118.88 ms
msgspec: 42.96 ms

Process finished with exit code 0
``` 
Thanks for your help.

**Comment by jcrist** [comment]
Glad you figured it out! Closing.
