### ISSUE TITLE
Add support for `typing.ByteString`/`collections.abc.ByteString`

### ISSUE THREAD

**Issue by jcrist** [jcrist/msgspec#52]
When parsing type signatures for structs, it'd be useful to support a more abstract bytes-like object. For encoding this would result in no major changes (encoding only deals with concrete types). For decoding, this would decode the type as `bytes` (unless an extension type was used).

**Comment by jakirkham** [comment]
This would be great and supporting both makes sense.

It's worth noting [the docs]( https://docs.python.org/3/library/typing.html#typing.ByteString ) say...

> Deprecated since version 3.9: [`collections.abc.ByteString`]( https://docs.python.org/3/library/collections.abc.html#collections.abc.ByteString ) now supports `[]`. See PEP 585 and [Generic Alias Type]( https://docs.python.org/3/library/stdtypes.html#types-genericalias ).

**Comment by jakirkham** [comment]
Also interesting in `collections.abc.ByteString` they mention `memoryview`s are supported, but that doesn't appear to be the case.

```python
import collections.abc
import typing

print(isinstance(memoryview(bytes()), collections.abc.ByteString))
print(isinstance(memoryview(bytes()), typing.ByteString))
```

```
False
False
```

**Comment by jcrist** [comment]
Oh, interesting. That certainly seems like a bug (at least in the documentation). `mypy` does count memoryviews here. You can make the runtime check work by calling

```
collections.abc.ByteString.register(memoryview)
```

but that applies a global change that may break things elsewhere (but is probably harmless).

**Comment by jakirkham** [comment]
Good point

This upstream issue ( https://bugs.python.org/issue33864 ) looks related. Seems like there is confusion as to if/how this should be included

Independently does annotating with `memoryview` work currently?
