### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by Olegt0rr** [jcrist/msgspec#523]
### Description

Since the release of the current benchmark, the competing libraries have updated their performance. Pydantic introduced Rust into the core and greatly accelerated.

For the veracity of the benchmark, it would also be great to indicate the versions of the libraries being measured. And in the case of a pydantic, make a comparison with both versions.

**Comment by jcrist** [comment]
This was fixed in #524. Pydantic V2 is now compared in the benchmarks, and all benchmarks now include version information. Closing.
