### ISSUE TITLE
Support for attrs `field(validators=...)`

### ISSUE THREAD

**Issue by provinzkraut** [jcrist/msgspec#535]
### Description

It would be great if msgspec supported `field(validators=...)` for attrs classes.

This is adjacent to #494.

An issue I'm currently facing is that, since msgspec supports attrs classes natively, there is no way to get those validators to work; Msgspec doesn't call them and I also can't make sure they're called via a `dec_hook`. 

A way to get this to work would be quite nice (=

**Comment by provinzkraut** [comment]
> Many of the builtin attrs validators are already supported in msgspec via other mechanisms, and will be both slower and duplicate work

No argument there. This definitely makes sense that if you're already using msgspec. However, my use case is - as usual - Litestar, where we swapped to msgspec for our internal parsing and validation needs. This includes handling of attrs classes a user has passed in. 

The concrete issue there is that we currently have no way to validate those correctly, whereas prior to msgspec adding support for attrs we could via an `enc_hook`.
So essentially the issue here for us is that msgspec only has partial support for decoding/converting into attrs, but no way to override its attrs handling.

I'm not sure how far along you are in the decision making process of finding a "better way" to handle the hooks (i.e. the one that would allow to override natively supported types), but I feel like that would quite often be a solution to the issues that arise due to different use cases.

**Comment by FHU-yezi** [comment]
We do need a way to add custom validator to Struct class.

I'm building a 3rd-party SDK for a platform, in my case, we need to validate if the provided `url` is valid or not, by sending an API call to an endpoint.

```python
class User(msgspec.Struct):
    url: str  # How can I do custom validate?
```

In Pydantic, I can do this:

```python
class User(Model):
    url: str

    @field_validator("url")
    @classmethod
    def validate_url(cls, value: str) -> str:
        if not is_user_url_valid(value):
            raise ValueError("User URL invalid")
        return v
```

**Comment by jcrist** [comment]
> We do need a way to add custom validator to Struct class.

This is unrelated to this issue. #483 is the issue tracking that feature.

> in my case, we need to validate if the provided url is valid or not, by sending an API call to an endpoint.

Are you saying you make an API call during validation? If so, I wouldn't handle that there (even when using pydantic) - making an API call everytime a `User` instance is created seems wasteful, and having side effects like an API call hidden inside a constructor may make it easy to miss that the API call is happening. It also won't compose well if working with async pythong.

Instead, I'd handle this separately outside of the JSON decoding, so it's explicit when the API request is being made. Something like:

```python
user = msgspec.json.decode(msg, type=User)
user.validate_url()  # explicit when the URL validating request happens
await user.validate_url()  # could even make it async if needed
```
