### ISSUE TITLE
Suggestion: make `forbid_unknown_fields` default to `True`

### ISSUE THREAD

**Issue by ccrvlh** [jcrist/msgspec#545]
### Description

Currently `forbid_unknown_fields` is set to `False` by default, for new users (like me) that are used to `dataclasses`, `Pydantic` etc, this can be somewhat confusing, and I confess it took me a while to find out what I was doing wrong (I was using keywords like `extra`, `allow` etc).

```python
import msgspec
import json

from typing import Optional


class User(Struct):
    name: str
    age: Optional[int] = None


valid = {
    "name": "John",
    "age": 42
}

invalid = {
    "name": "John",
    "age": 42,
    "foo": "bar"
}

valid_payload = json.dumps(valid).encode('utf-8')
invalid_payload = json.dumps(invalid).encode('utf-8')

# This is valid
msgspec.json.decode(valid_payload, type=User)

# This is also valid, suggesting this to be invalid by default
msgspec.json.decode(invalid_payload, type=User)

# Now this is invalid and raises
msgspec.json.decode(invalid_payload, type=User, forbid_unknown_fields=True)
```

My suggestion here is to have this set as `True` by default, since initializing a structure with an unknown set of keyword arguments raises an exception in most cases (regular classes, dataclasses, etc).

**Comment by FHU-yezi** [comment]
I think keeping this selection as False by default is a better solution.

First of all, the documentation of Msgspec has a paragraph about "incremental enhancements", meaning that you can add new fields if you don't change the order of fields and set a default value for each new field, applications that don't upgrade to the new version yet will automatically ignore the new field when parsing the new version of the data structure, rather than throwing an error.

Additionally, when building a type-safe wrapper for some APIs, we may only need a portion of all the fields, ignoring unknown fields by default reduces the deserialization overhead and helps to write cleaner code.

Finally, this is going to be a breaking change, so we'll have to release it in the next big release.

**Comment by ccrvlh** [comment]
Hey thanks for sharing this.

Mind sharing the "incremental enhancements" part? Is that related to dynamic manipulation of structs? I couldn't find it when searching the docs.

Also, allow me to disagree with this statement in particular:

> Additionally, when building a type-safe wrapper for some APIs, we may only need a portion of all the fields, ignoring unknown fields by default reduces the deserialization overhead and helps to write cleaner code.

IME type-safe wrappers should also be predictable and (mostly) explicit, this is clean. By just ignoring fields, we are not making the client aware that there has been an error (something that the client explicitly wants to be considered is just being ignored). I'm not sure overhead is that relevant here: the check can happen exactly at the same time when your initializing the struct, if it doesn't exist, just raise an error. Also don't imagine this would be expensive in terms of performance. I just don't see "invisible" behavior as cleaner, quite the opposite.

About the breaking change - definitely something relevant and to be considered only for next major releases.

**Comment by FHU-yezi** [comment]
About "incremental enhancements", which called "Schema Evolution" in the doc: https://jcristharif.com/msgspec/schema-evolution.html

When validating requests/responses of the API, we absolutely need to forbid unknown fields, which helps to make any unnoticed spelling errors visible.

According to the documentation's "Performance Tips" page, avoiding deserialization of unneeded fields can help improve performance.

**Comment by janluke** [comment]
> Currently forbid_unknown_fields is set to False by default, for new users (like me) that are used to dataclasses, Pydantic etc,

Pydantic actually has the same default behavior: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra

**Comment by ccrvlh** [comment]
@janluke you're right, I've been using dataclasses more often and for some reason had the wrong memory of Pydantic's behavior.

@FHU-yezi thank you for the reference, went through the docs and agree with you, I think allowing it is a better default, I'm closing this.
