### ISSUE TITLE
Special Characters in Field Names

### ISSUE THREAD

**Issue by black-tea** [jcrist/msgspec#547]
### Description

Thanks for this library! I have just started exploring it, and after reading through the docs, I can't figure out how to handle decoding JSON that uses python special characters as the field names, since we specify the field names as class attributes. Do you have any guidance on how I could handle the JSON that looks like `{"@id": 2, "another_field": "some_value}`

**Comment by uglybug** [comment]
This is documented in the homepage: https://jcristharif.com/msgspec/structs.html#renaming-fields
```
class Example(msgspec.Struct):
   id: int = msgspec.field(name="@id")
   another_field: str

msgspec.json.decode(b'{"@id": 1, "another_field": "some_value"}', type=Example)
# Example(id=1, another_field='some_value')
```

**Comment by jcrist** [comment]
The above response is correct, see https://jcristharif.com/msgspec/structs.html#renaming-fields for reference. Closing.
