### ISSUE TITLE
Dynamic model creation at runtime

### ISSUE THREAD

**Issue by gsouveton** [jcrist/msgspec#554]
### Description

I'm planning to replace Pydantic with msgspec in different projects I'm working on.
However, there's an important feature in Pydantic which is dynamic model creation, with the create_model (https://docs.pydantic.dev/latest/api/base_model/#pydantic.create_model) that allows to define schemas at runtime based on a dynamic configuration.
Is this feature something that msgspec will be able to do ? Or maybe it may imply too significant performance drawbacks ?

**Comment by provinzkraut** [comment]
There is the `defstruct` function which should be exactly what you're looking for:

https://jcristharif.com/msgspec/structs.html#runtime-definition

**Comment by jcrist** [comment]
Yep, `msgspec.defstruct` is the way to do this - should have comparable functionality to `pydantic.create_model`/`dataclasses.make_dataclass`/`attrs.make_class`.
