### ISSUE TITLE
Thanks to encoding hooks, why not supporting arbitrary objects as dict keys?

### ISSUE THREAD

**Issue by shangoue** [jcrist/msgspec#568]
### Description

First, thanks for this great library!
I would like to serialize a dict whose keys are instances of a class coming from another library. I am already able to serialize these objects using enc_hook parameter to convert them as strings. But if these objects are converted to strings, why we cannot use them as keys for json dict ?

Here is a minimalist example:

```python
from typing import Any, Dict, Type
import msgspec

class OpCode:
    pass

def enc_opcode(obj: Any):
    if isinstance(obj, OpCode):
        return "opcode"
    raise NotImplementedError(f"Cannot serialize {type(obj)}")

data = {}
data[OpCode] = 1
msgspec.json.encode(data, enc_hook=enc_opcode)
```

**Comment by jcrist** [comment]
Thanks for opening this; you've found a bug! This currently works correctly for `msgspec.msgpack.decode` and `msgspec.convert`, but fails for `msgspec.json.decode`. Will fix.
