### ISSUE TITLE
Support for `dataclass`es

### ISSUE THREAD

**Issue by jakirkham** [jcrist/msgspec#57]
Given the close similarity between [`msgspec.Struct`]( https://jcristharif.com/msgspec/api.html#msgspec.Struct ) and [`dataclasses.dataclass`]( https://docs.python.org/3/library/dataclasses.html ), am curious to what extent `dataclass`es can be used with `msgspec` and what this entails.

**Comment by goodboy** [comment]
Pretty sure you can write a custom codec to handle them as per: https://jcristharif.com/msgspec/extending.html#mapping-to-from-native-types

**Comment by jcrist** [comment]
Dataclasses aren't natively supported, but could be handled with a custom `enc_hook` and `dec_hook`. However, this will be slow (much slower than using a `msgspec.Struct` or using a raw `dict`). While structs and dataclasses have similar apis, its the internal design of struct types that makes them so fast. We *could* add native support for dataclasses which would put them somewhere between structs and dicts in encode speed (faster than a dict, slower than a struct), but for decoding they'd still be slower than a dict. If possible I recommend people just use structs - they're fast and support most of the things people want in dataclasses.

**Comment by old-ocean-creature** [comment]
>  they're fast and support most of the things people want in dataclasses

This is true except there is an ecosystem of tooling around dataclasses, adopting `msgspec.Struct` means disconnecting from that ecosystem

**Comment by jcrist** [comment]
What libraries/tools are you thinking of that support dataclasses that you'd also like to use with msgspec?

**Comment by provinzkraut** [comment]
Hi there. So, while trying to make the switch from orjson to msgspec for Starlite, I encountered this issue. The main concern here is performance really. Dataclasses are natively supported by orjson; Their serialization is therefore quite fast. 
What this means for us is, that making the switch to msgspec would be a massive drop in performance for our users when dataclasses are being used. 

You can see below a simple benchmark result comparing the branch with orjson and the branch with msgspec.

![rsz_rps_serialization](https://user-images.githubusercontent.com/25355197/204876117-a576a3c1-99b1-4da6-9356-c487d8f5cb74.png)

I'm not sure how much work implementing dataclasses support would be, I just wanted to let you know of this use case where dataclass support is kinda vital, so you can consider if you deem it to be worth the effort.

**Comment by Goldziher** [comment]
fantastic! were are eagerly awaiting 😉

**Comment by provinzkraut** [comment]
@jcrist Thank you for your fantastic work on this and your responsiveness to the issues we raised here in general!

**Comment by jcrist** [comment]
Ok, #218 is in - `msgspec` now supports encoding/decoding dataclasses. This came together a lot quicker than I expected, and was pretty fun to work on. They're not as performant or featureful as `Struct` types, but perforamance isn't bad (especially for encoding).

I have a few other small fixups I'd like to get in, I'd expect a release sometime next week.

**Comment by jakirkham** [comment]
Thanks Jim! 🙏

**Comment by provinzkraut** [comment]
It's working fantastic! I ran the benchmark again and we can see some real improvements!

![rps_serialization](https://user-images.githubusercontent.com/25355197/205261102-5a5b96a1-0830-46cd-9b4b-b105a120260c.svg)
