### ISSUE TITLE
`defstruct` with `default_factory ` and/or `FieldInfo`

### ISSUE THREAD

**Issue by alexei** [jcrist/msgspec#580]
### Description

Currently `defstruct` offers no way of declaring a field with a `default_factory`, but this could be useful when e.g. defining structs from dataclasses. Is there any chance of supporting this?

Or maybe even with `FieldInfo` à la:

```python
defstruct(
    "Foo",
    (
        ("field1", FieldInfo(default="val1", ...)),
        ("field2", FieldInfo(default_factory=datetime.now, ...)),
        ...
    ),
)
```

**Comment by jcrist** [comment]
This is currently supported by passing a `msgspec.field` as the third item in a field tuple:

```python
from datetime import datetime

from msgspec import defstruct, field


Foo = defstruct(
    "Foo",
    [
        ("field1", str, "val1"),
        ("field2", datetime, field(default_factory=datetime.now)),
    ],
)


print(Foo())
#> Foo(field1='val1', field2=datetime.datetime(2023, 11, 6, 22, 47, 19, 814065))
```

Is there a way this could be made clearer in the [docs](https://jcristharif.com/msgspec/api.html#msgspec.defstruct)? If so, PRs welcome!

**Comment by jcrist** [comment]
Closing as stale/resolved.

**Comment by alexei** [comment]
I opened a PR, see https://github.com/jcrist/msgspec/pull/586
