### ISSUE TITLE
Is encoding with `msgspec` faster than to `json.dumps(dataclass.asdict)`?

### ISSUE THREAD

**Issue by remiconnesson** [jcrist/msgspec#589]
### Question

Hello sorry if the question is dumb as `json.dumps(dataclass.asdict)` does not perform any validation and `msgspec` seems to do.

But I'm still wondering, if `msgspec` would be faster in encoding without validation as maybe you are using a different mechanism to encode in `JSON`?

Thank you very much

**Comment by CamDavidsonPilon** [comment]
Hi @remiconnesson, msgspec doesn't validate on `encode` (the equivalent of `dump`), only on `decode` (`loads`): https://jcristharif.com/msgspec/structs.html#type-validation

**Comment by remiconnesson** [comment]
Thank you very much for the clarification @CamDavidsonPilon and pointing out to this page

from the initial paragraph:
```
Structs are the preferred way of defining structured data types in msgspec. They’re written in C and are quite speedy and lightweight ([measurably faster](https://jcristharif.com/msgspec/benchmarks.html) to create/compare/encode/decode than similar options like [dataclasses](https://docs.python.org/3/library/dataclasses.html), [attrs](https://www.attrs.org/en/stable/index.html), or [pydantic](https://pydantic-docs.helpmanual.io/)). They’re great for representing structured data both for serialization and for use in an application.
```

I take it as a yes :)

**Comment by CamDavidsonPilon** [comment]
Yes, you can have look at the benchmarks to get a good idea: https://jcristharif.com/msgspec/benchmarks.html#benchmark-encoding-decoding

But also you can run some perf tests locally to see as well!

**Comment by jcrist** [comment]
As mentioned above, encoding dataclasses with msgspec is much faster than doing `json.dumps(dataclass.asdict(obj))`. When you have questions like this, I recommend doing benchmarks yourself locally to measure things yourself. Here's a quick benchmark to get you started:

```python
In [1]: import msgspec, dataclasses, json

In [2]: @dataclasses.dataclass
   ...: class Point:
   ...:     x: int
   ...:     y: int
   ...:     z: int
   ...: 

In [3]: p = Point(1, 2, 3)

In [4]: %timeit msgspec.json.encode(p)
144 ns ± 0.321 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [5]: %timeit json.dumps(dataclasses.asdict(p))
4.58 µs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [6]: print(f"msgspec encoded dataclasses to JSON {4.58 / .144:.1f}x faster")
msgspec encoded dataclasses to JSON 31.8x faster
```
