### ISSUE TITLE
Converting dicts into list with key-reuse

### ISSUE THREAD

**Issue by hynek** [jcrist/msgspec#643]
### Question

As briefly discussed on Mastodon, here’s a more verbose version:

I’ve got JSON that looks vaguely like this:

```json
{
  "server": "mb10",
  "mailboxes": {
    "user1@example.com": {
      "size": 22304
    }
  }
}
```

and I would like to get something like this:

```python
@define
class Mailbox:
    name: str # <- this is where the key goes
    size: int

@define
class Server:
    server: str
    mailboxes: list[Mailbox]
``` 

can this be achieved with msgspec?

**Comment by jcrist** [comment]
There's no native way to spell this cleanly right now (I'm not even sure what am API for that might look like), but this pattern can be supported in a few different ways through extensions. Do you also need to reserialize the data in the same format? Or is this for decoding only?

**Comment by hynek** [comment]
> There's no native way to spell this cleanly right now (I'm not even sure what am API for that might look like), but this pattern can be supported in a few different ways through extensions. Do you also need to reserialize the data in the same format? Or is this for decoding only?

I do not, but you also don't have to add any functionality just for me. :) I can achieve that using an extra transformation step as outlined by Blake – I was just surprised that I couldn't find a straight-forward solution to an ostensibly common problem in _any_ serialization package so I thought I'd ask around if I'm missing something. :)

Thanks for humoring me!
