### ISSUE TITLE
Support `Literal` type

### ISSUE THREAD

**Issue by CamDavidsonPilon** [jcrist/msgspec#65]
:wave: what are your thoughts on supporting the `Literal` type?

**Comment by CamDavidsonPilon** [comment]
Simply: I have existing types that use `Literal`:

```python
PdChannel = Literal["1", "2"]

...

class ODReadings(Struct):
    timestamp: str
    od_raw: dict[PdChannel, ODReading]

msgspec.json.decode(..., type=ODReadings) # TypeError: Type 'typing.Literal['1', '2']' is not supported
```

**Comment by jcrist** [comment]
Cool, yeah, I can definitely add support for this. Adding it to the queue, thanks for the suggestion!

**Comment by jcrist** [comment]
Thanks for the issue request, this has been fixed in #71. I have a few small fixups I hope to get in before releasing, but feel free to try this out from the main branch if you're interested:

```
pip install git+https://github.com/jcrist/msgspec
```

**Comment by CamDavidsonPilon** [comment]
Already trying it :)

Thanks for devoting time to this, @jcrist!

**Comment by jcrist** [comment]
This has now been released. Up on pypi now, should be on conda-forge shortly.
