### ISSUE TITLE
Plugin for PyCharm / VS Code

### ISSUE THREAD

**Issue by janluke** [jcrist/msgspec#712]
### Description

Is there any plan to develop plugins for the main IDEs to provide autocomplete?

**Comment by jcrist** [comment]
There shouldn't be a need for a plugin for most tools. We make use of standard type annotations including [PEP 681](https://peps.python.org/pep-0681/). `mypy` and `pyright` work out-of-the-box (which means VS Code does too). I have no plans to develop a PyCharm plugin (I'm not even sure if that's possible). See [this pycharm issue](https://youtrack.jetbrains.com/issue/PY-54560) for PEP 681 support in pycharm - if you want better autocomplete for `msgspec` and other tools (like SQLAlchemy), this is the issue that would need to be resolved.
