### ISSUE TITLE
Collect all ValidationErrors instead of failing fast

### ISSUE THREAD

**Issue by chuckwondo** [jcrist/msgspec#721]
### Description

It would be nice to be able to identify multiple ValidationErrors at a time rather than failing fast on the first ValidationError encountered.

For example, given this Struct:

```python
class Position(msgspec.Struct, array_like=True):
    longitude: Annotated[float, msgspec.Meta(ge=-180.0, le=180.0)]
    latitude: Annotated[float, msgspec.Meta(ge=-90.0, le=90.0)]
```

If we decode data where _both_ values are out of range, we get only _one_ validation error:

```
>>> msgspec.json.decode('[-200, 100]', type=Position)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
msgspec.ValidationError: Expected `float` >= -180.0 - at `$[0]`
```

It would be helpful for _both_ errors to be identified.

@jcrist, I've opened a few issues recently, but I'm more than happy to dig into the code to attempt creating some PRs, but I will likely need some pointers.

**Comment by provinzkraut** [comment]
Non-authoritative response, but @jcrist has [made a statement](https://github.com/litestar-org/litestar/pull/1854#discussion_r1247379349) about not wanting to support this before.

**Comment by chuckwondo** [comment]
> Non-authoritative response, but @jcrist has [made a statement](https://github.com/litestar-org/litestar/pull/1854#discussion_r1247379349) about not wanting to support this before.

@provinzkraut, thank you for pointing that out. I couldn't manage to find prior, related discussions, so I appreciate your pointing me in the right direction. I had a feeling the answer would be along the lines covered in that thread, so I'll close this issue.
