### ISSUE TITLE
Best way to encode large JSON plain text into msgpack struct and filter entries

### ISSUE THREAD

**Issue by deajan** [jcrist/msgspec#733]
### Question

Hello,

I have a program that produces millions of json lines it prints to stdout that look like:
```
{"name": "b458b848.2024``04-28-13h07.gz", "type": "file", "path": "/path/b458b848.2024-04-28-13h07.gz", "uid": 0, "gid": 0, "size": 82638431, "mode": 438, "permissions": "-rw-rw-rw-", "mtime": "2024-04-29T10:32:18+02:00", "atime": "2024-04-29T10:32:18+02:00", "ctime": "2024-04-29T10:32:18+02:00", "message_type": "node", "struct_type": "node"}
```

So far, I've replaced standard json implementation with msgspec.json like this:
```
my_result = []
for line in plain_output:
    my_result.append(msgspec.json.decode(line))
```

So `msgpack.json.decode` is a good drop in replacement for `json.loads` so far, but I'm still using way to much memory (lowered from 1035MB to 860MB by switching json implementation).

I'd like to use a msgpack struct like form instead json objects, in order to lower memory usage.
I've read the documentation, but I'm not sure how to achieve the following:

In the above record, I only need some fields so I created a class like this:  
Note: I know I didn't parse the datetime format yet, but it may vary from platform to platform so I prefer using str
```
class LsNode:
    """
    restic ls outputs lines of 
    {"name": "b458b848.2024-04-28-13h07.gz", "type": "file", "path": "/path/b458b848.2024-04-28-13h07.gz", "uid": 0, "gid": 0, "size": 82638431, "mode": 438, "permissions": "-rw-rw-rw-", "mtime": "2024-04-29T10:32:18+02:00", "atime": "2024-04-29T10:32:18+02:00", "ctime": "2024-04-29T10:32:18+02:00", "message_type": "node", "struct_type": "node"}
    """
    name: str
    type: str
    path: str
    size: int
    mtime: str

my_result = []
for line in plain_output:
    my_result.append(msgspec.msgpack.encode(msgspec.json.decode(line, type=LsNode)))
```

I'm pretty sure the must be a better way to convert a plaintext string to a msgpack struct object and filter content based on a class.
I've read the doc but I didn't find an elegant solution.
Could anyone point me in the right direction please ?

Also, when I try to access any object like `my_result[0].path` I get `AttributeError: 'bytes' object has no attribute 'path'`. Pretty sure my above code is messed up.

Last point, in the above object, I store objects in a list, but since struct objects can be nested, I could create a "msgpack struct list of msgpack entries" probably. Would this benefit anything ? If so, how do I achieve this ? This way ?
```
class LsNodes:
    nodes: LSNode
```

Thanks.

**Comment by jack-mcivor** [comment]
```python
my_result = []
decoder = msgspec.json.Decoder(LsNode)
for line in plain_output:
     my_result.append(decoder.decode(line))
```

Using a Struct (typed decoding) will reduce memory as you'll only decode the attributes defined on the class. In the above example I also a define a `Decoder` which is reused.

I think maybe there is a bit of confusion as to what msgpack is. It is a serialized format, a bit like a unreadable form of json. When you call `msgpsec.msgpack.encode`, you are serializing the data into `bytes`. That form is suitable for writing to disk or sending on the network. That's why you got the error about indexing a bytes object.

If you want to reduce memory, the best way is to not require your whole input in memory at once (`plain_input`) or not accumulate all the results in memory at once (`my_result`). Not sure if that's possible for your use case though.

If you can, you could choose to use a msgpack format for your original data instead of json. If your data is msgpack encoded, you can just switch `msgspec.json` -> `msgspec.msgpack` in the above example. There are some tradeoffs though - the data is no longer human readable and you won't be able to use line breaks to delimit objects (eg. length-prefix framing).

> Last point, in the above object, I store objects in a list, but since struct objects can be nested, I could create a "msgpack struct list of msgpack entries" probably. Would this benefit anything ?

I don't really think there is a benefit to doing this in your case.

Apologies if I've missed the mark. Let me know if that helps you

**Comment by deajan** [comment]
@jack-mcivor Thanks, that explanation makes sense.

My source spits json, so yes, I'll have to use the decoder, and yes i need the whole data in memory to construct an object from it.
I initially thought I could use `msgpack` as my "in memory representation" of the data and access the msgpack data with dot notation or something alike. As of your message I now do understand that the `msgapck` representation is used for storage / sending but not data handling in variables.

I'll use your above example and report back what kind of memory savings I can achieve with this.
Thank you.

**Comment by jack-mcivor** [comment]
@deajan a couple of other thoughts for you.

Make sure you don't have all your input data in memory at once. A pattern like the following will read from the file one line at a time.

```python
with Path("some/file").open() as f:
    for line in f:
        decoded_data = decoder.decode(line)
```

**Comment by deajan** [comment]
@jack-mcivor Again, thank you for your time.

As I get my plain_output from a subprocess call, unless I implement stdout queues, I won't be able to iter over output without actaully reading it fully into memory.

I've implemented msgpack into my program, and here are the results so far:

| Program | Memory usage |
|----------|----------|
| NPBackup v3rc5+dev viewer x64 windows vanilla | 1035MB |
| NPBackup v3rc5+dev viewer x64 windows with msgspec json drop-in | 860MB | 
| NPBackup v3rc5+dev viewer x64 windows with msgspec json drop-in and struct usage | 660MB | 
| NPBackup v3rc5+dev viewer x64 windows with msgspec json drop-in, struct data representation and manual garbage collection | 648MB |
| NPBackup v3rc5+dev viewer x64 windows with msgspec json drop-in, struct data representation, manual garbage collection and StrEnum for type | 635MB |
| NPBackup v3rc5+dev viewer x64 windows with msgspec json drop-in, struct data representation and manual garbage collection | 648MB |
| NPBackup v3rc5+dev viewer x64 windows with msgspec json drop-in, struct data representation, manual garbage collection and timestamp / name improvements | 622MB |

I was not able to implement IntEnum since I deal with strs, I guess you meant StrEnum ? Got me about 15MB savings.

I've implemented the timestamp representation (have me another 15MB savings) and removed name to extract it from path.
The timestamp to strftime (I need a str) costs 5 seconds exec time, but I think it's worth it.

Simply swapping the json implementation got 17% memory improvement and made execution time fall from 25 to 7 seconds.
Applying Struct representation and optimizing made a whopping 40% memory usage improvement while execution time is still better (12 seconds instead of 25).

So all in all, thank you for your help.
