### ISSUE TITLE
Do you mind me package this into nixpkgs?

### ISSUE THREAD

**Issue by luochen1990** [jcrist/msgspec#739]
### Question

[nixpkgs](https://github.com/NixOS/nixpkgs) is a popular package repository and it is reproducibility.

**Comment by jcrist** [comment]
Please feel free to, thanks for asking.

**Comment by luochen1990** [comment]
Thanks, It's already done:  https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=msgspec
