### ISSUE TITLE
Extend dict keys to allow for string literals?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [jcrist/msgspec#76]
Currently, string literals can't be used as dict keys in a `Struct`. See example below:

```python
from typing import Literal
from msgspec import Struct, json

AorB = Literal["a", "b"]

class Test(Struct):
    d: dict[AorB, float]

data = Test(d={'a': 1.0, 'b': 2.0})
encoded = json.encode(data)
print(encoded)

decoded = json.decode(encoded, type=Test) # TypeError: JSON doesn't support dicts with non-string keys - type `dict[typing.Literal['a', 'b'], float]` is not supported
```

I would think it _should_ be allowed - but I'd like  to hear your thoughts.

**Comment by jcrist** [comment]
Yeah, this definitely should be allowed, thanks for the issue. Will fix.

**Comment by jcrist** [comment]
I'm curious though - why write things this way instead of either:

- Using a struct with `a` and `b` fields
- Using a [typing.TypedDict](https://docs.python.org/3/library/typing.html#typing.TypedDict) (not currently supported, but could be?).

**Comment by CamDavidsonPilon** [comment]
👍 

My example does look silly to write this way, but my IRL use case looks like:

```
PdChannel = Literal["1", "2"]

class ODReadings(Struct):
    timestamp: str
    od_raw: dict[pt.PDChannel, ODReading] 
```

Because the `PdChannel`s are numbers, I can't use them as keys / attrs!

**Comment by jcrist** [comment]
Gotcha, that makes sense.

I found it a bit unclear in the `TypedDict` docs  (https://docs.python.org/3/library/typing.html#typing.TypedDict), but after some experimentation it looks like you can define a `TypedDict` with keys that aren't valid python identifiers, just not using the subclass-based form.

```python
from typing import TypedDict


Example = TypedDict("Example", {"$x": int, "y": int, "z\nz2": int})


def test(ex: Example) -> int:
    return ex["$x"] + ex["y"] + ex["z\nz2"]


test({"$x": 1, "y": 2, "z\nz2": 3})  # ok

test({"$x": 1, "y": 2, "z\nz2": 3, "oops": 4})  # extra key

test({"$x": 1, "y": 2})  # missing key

test({"$x": "oops", "y": 2, "z\nz2": 3})  # wrong value type
```

```
$ mypy example.py
example.py:13: error: Extra key "oops" for TypedDict "Example"
example.py:15: error: Missing key "z
z2" for TypedDict "Example"
example.py:17: error: Incompatible types (expression has type "str", TypedDict item "$x" has type "int")
Found 3 errors in 1 file (checked 1 source file)
```

So in your case, the following would be the equivalent I think:

```python
# Use total=False to state that all fields are optional (which is equivalent to the Literal
# based definition above). If instead they're all required, then the default of `total=True`
# is what you'd want.
ODRaw = TypedDict("ODRaw", {"1": ODReading, "2": ODReading}, total=False)
```

I don't plan to get to it any time soon, but I'll open an issue for supporting `TypedDict` types since they seem useful in some situations.

**Comment by CamDavidsonPilon** [comment]
> just not using the subclass-based form.

huh, that's interesting! Thanks for explaining this!
