### ISSUE TITLE
New release for Python 3.13

### ISSUE THREAD

**Issue by lesleslie** [jcrist/msgspec#764]
### Question

Hello,

Wondering when we can expect a new release compatible with Python 3.13?

I see the commit for the Python 3.13, and am able to install it using git+https://github.com/jcrist/msgspec.git, but unfortunately I can't publish any packages to pypi that depend on msgspec until a new official release has been published to pypi. Am hoping for a new release soon that incorporates the Python 3.13 support (without freethreading for now).

Thank you!

-- les

**Comment by lesleslie** [comment]
As a temporary workaround I created a package with python 3.13 support. I wouldn't expect this to be updated or maintained beyond this point but give it try if you like. It will be deleted once a new official release comes out.

msgspec-python313-pre

`pdm add msgspec-python313-pre` or whatever

**Comment by Tishka17** [comment]
@jcrist hi, what are current plans about publishing release?

**Comment by Zaczero** [comment]
It seems like he is currently working on adding free-threading support, so my only assumption would be that he wants to release the new version with it already included. [Reference](https://bsky.app/profile/jcristharif.bsky.social/post/3latskqv7722e). I also think some communication on these issues wouldn't hurt!

**Comment by astrojuanlu** [comment]
I'm pretty sure the maintainers know of the community excitement around 3.13 and adding more "+1" messages will not help. Maintainer attention is a scarce resource, please be considerate. Many of us are subscribed to this issue for updates. Peace and love 🕊️

**Comment by kamikaze** [comment]
please 😭

**Comment by piotrm-nvidia** [comment]
pls pls

**Comment by return42** [comment]
Really love mesgspec but without python 3.13 its not any longer an option .. distros with rolling releases started to switch to Python 3.13 .. ArchLinux is one -> and our applications did stop working .. 

> I'm pretty sure the maintainers know of the community excitement around 3.13 and adding more "+1" messages will not help. 

Fully understand ..  especially as I am a developer myself, but leaving such major problems uncommented is not a solution either 

-> users now have to deal with [broken applications](https://github.com/searxng/searxng/issues/4015#issuecomment-2561292731) ..

I apologize for the harsh tone, but I wanted to make it clear: We need a timeline!

**Comment by jcrist** [comment]
msgspec 0.19.0 has been released with support for Python 3.13. The full changelog may be found [here](https://jcristharif.com/msgspec/changelog.html#version-0-19-0-2024-12-27).

Thank you everyone for your patience. Closing.

**Comment by return42** [comment]
> Thank you everyone for your patience. Closing.

Thank you for responding to my request so quickly :+1:

**Comment by return42** [comment]
>  It will be deleted once a new official release comes out.

@lesleslie its out now, you can remove your package from pypi .. thanks a lot for your interim solution.

**Comment by lesleslie** [comment]
@return42 @jcrist msgspec-python313-pre has been deleted from pypi.  thank you everyone!

**Comment by nhairs** [comment]
> `msgspec-python313-pre` has been deleted from pypi. thank you everyone!

FYI, deleting `msgspec-python313-pre` left users open to a potential supply chain attack (e.g. [GHSA-wmxh-pxcx-9w24](https://github.com/nhairs/python-json-logger/security/advisories/GHSA-wmxh-pxcx-9w24)).

If it is still in your dependencies you should remove it.
