### ISSUE TITLE
How to get access to the tag field in a tagged union

### ISSUE THREAD

**Issue by richardshephard1** [jcrist/msgspec#768]
### Question

We use tagged unions, but we need access to the tag field as there are some dynamic elements that we mutate the tag field based on some other data when creating model for JSON serialization. However, the tag field is not available when using the tag union structures.

A more concrete example is that we have a tree structure that we translate from a tree to a different tree. The first tree is basically a dictionary of lists, and the second is a msgspec.Struct list of union types:
```python
class EmbeddedLink(Struct, tag=True):
    type: str
    children: list[StyledText]
    link: ReferenceLink

    @classmethod
    def from_rte_node(cls, node: dict):
        return EmbeddedLink(
            type=node["type"],
            children=[StyledText.from_rte_node(child) for child in node["children"]],
            link=ReferenceLink(
                href=node["attrs"]["url"],
                target=node["attrs"].get("target"),
            ),
        )
```

Each of those "type" tag comes from the first tree that isn't known, but we only know the type once we walk the tree to create the list of types. We've got dynamic "type"s arriving so hardcoding the "type" in a class become a maintenance issue to keep updating and creating classes for the type changes. 

The problem above is a little contrived, but the more complex scenarios are harder to describe without a lot more code around.

Is there a way of changing/accessing the type field for the tag?

**Comment by chuckwondo** [comment]
I suggest you look at [Runtime Definition](https://jcristharif.com/msgspec/structs.html#runtime-definition) (see [defstruct](https://jcristharif.com/msgspec/api.html#msgspec.defstruct)).

I imagine something along these lines might do what you're looking for:

```python
class EmbeddedLink(Struct):
    children: list[StyledText]
    link: ReferenceLink

    @classmethod
    def from_rte_node(cls, node: dict):
        embedded_link = defstruct(f"{node['type']}EmbeddedLink", (), (EmbeddedLink,), tag=True)
        embedded_link.children=[StyledText.from_rte_node(child) for child in node["children"]]
        embedded_link.link=ReferenceLink(
            href=node["attrs"]["url"],
            target=node["attrs"].get("target"),
        )

        return embedded_link
```

**Comment by richardshephard1** [comment]
Oh, nice - that's an interesting way round the problem ... needs some tweaking, but looks promising - thanks 👍
