### ISSUE TITLE
Backport type annotation syntax support for older python versions

### ISSUE THREAD

**Issue by jcrist** [jcrist/msgspec#771]
Pydantic handles this via https://github.com/alexmojaki/eval_type_backport -- is there any appetite for doing the same in msgspec? Happy to PR it if that it'd be supported.

_Originally posted by @ashb in https://github.com/jcrist/msgspec/issues/737#issuecomment-2470956504_

**Comment by ashb** [comment]
In terms of effort I can spare l make time to do no.1, not sure I've got the spare cycles to do a full implementation.

Happy to pr approach 1

**Comment by jcrist** [comment]
Sounds good to me, thanks!

**Comment by ashb** [comment]
@jcrist Re testing: am I right in thinking that the cibuildwheel will test against multiple versions of python, so do I need to convice the GHA  pipeline to run 3.9 with and without the dep installed?

**Comment by jcrist** [comment]
There are ways to hack in testing without it I installed that wouldn't require another ci build - if you could just write tests for behavior with it installed I can add/fixup those afterward.
