### ISSUE TITLE
How to use Meta to add and access description of a field

### ISSUE THREAD

**Issue by jacopoabramo** [jcrist/msgspec#783]
### Question

I want to create a msgspec.Struct with annotated types that provide a description of that field; I want to use the description field to provide a human-readable string that I would like to use in an UI application to provide an informative tooltip of what that field represents. I understand Meta helps with that, but after creating the object I don't know how to dynamically access the description field. A minimum example:

```py
from msgspec import Struct, Meta
from typing import Annotated

class Point(Struct):
    x: Annotated[int, Meta(description="The x-coordinate")]
    y: Annotated[int, Meta(description="The y-coordinate")]

obj = Point(x=1, y=2)
```

**Comment by provinzkraut** [comment]
You can use the [`msgspec.inspect`](https://jcristharif.com/msgspec/inspect.html) module to safely extract metadata from structs and their fields, including metadata.

**Comment by jacopoabramo** [comment]
@provinzkraut thanks for the reply. I tried it out but apparently it only works for defined types while I would like to be able to introspect specific fields, i.e.

```python
print(obj.x.description)

# expected output: The x-coordinate
```

**Comment by provinzkraut** [comment]
What's the benefit of accessing the metadata this way? It will always be the same for every instance of the type. Anyway, you could just do `type(obj)` to get the class and then do the introspection on that.

**Comment by jacopoabramo** [comment]
> It will always be the same for every instance of the type.

Didn't think of that, makes sense. I'll go with the suggested approach. Closing.
